/**
 * Refresh the bundled free-market USD→IRT history.
 *
 *   npm run fx:history
 *
 * Downloads the public daily series of the free-market dollar (TGJU
 * `price_dollar_rl`, Rial, back to ۱۳۹۰) and rewrites
 * `src/features/fx/historicalUsdIrtData.ts` as Toman daily closes. The app never
 * calls the provider at runtime — a purchase date is looked up in that file.
 */
import fs from "node:fs";
import path from "node:path";

const SOURCE = "tgju:price_dollar_rl";
const URL =
  "https://api.tgju.org/v1/market/indicator/summary-table-data/price_dollar_rl?lang=fa&order_dir=asc&start=0&length=20000";
const OUT = path.resolve(process.cwd(), "src/features/fx/historicalUsdIrtData.ts");
const DAY_MS = 86_400_000;

// Columns: open, low, high, close, change, change %, Gregorian date, Jalali date.
const CLOSE = 3;
const GREGORIAN = 6;

const rialOf = (cell: unknown) => Number(String(cell ?? "").replace(/[^\d]/g, ""));

async function main() {
  const res = await fetch(URL, { headers: { accept: "application/json" } });
  if (!res.ok) throw new Error(`TGJU responded ${res.status}`);
  const body = (await res.json()) as { data?: unknown[][] };

  const byDate = new Map<string, number>();
  for (const row of body.data ?? []) {
    const date = String(row[GREGORIAN] ?? "").replace(/\//g, "-");
    const toman = Math.round(rialOf(row[CLOSE]) / 10);
    // The same sanity band the rate settings enforce.
    if (/^\d{4}-\d{2}-\d{2}$/.test(date) && toman >= 1_000 && toman <= 10_000_000) byDate.set(date, toman);
  }
  const rows = [...byDate].sort(([a], [b]) => a.localeCompare(b));
  if (rows.length < 1_000) throw new Error(`Only ${rows.length} usable rows — refusing to overwrite the bundled history.`);

  const first = Date.parse(`${rows[0][0]}T00:00:00Z`);
  const series = rows.map(([date, toman]) => `${Math.round((Date.parse(`${date}T00:00:00Z`) - first) / DAY_MS)}:${toman}`);

  const file = `/* AUTO-GENERATED by src/scripts/build-historical-usd.ts — run \`npm run fx:history\` to refresh. */

/** Provider of the series (free-market dollar, daily close). */
export const HISTORICAL_USD_IRT_SOURCE = ${JSON.stringify(SOURCE)};
/** First and last Gregorian day covered. */
export const HISTORICAL_USD_IRT_FIRST = ${JSON.stringify(rows[0][0])};
export const HISTORICAL_USD_IRT_LAST = ${JSON.stringify(rows[rows.length - 1][0])};
/** "dayOffsetFromFirst:toman" pairs, ascending — ${rows.length} trading days. */
export const HISTORICAL_USD_IRT_DAYS =
  ${JSON.stringify(series.join(","))};
`;
  fs.writeFileSync(OUT, file);
  console.log(`Wrote ${rows.length} days (${rows[0][0]} → ${rows[rows.length - 1][0]}) to ${path.relative(process.cwd(), OUT)}`);
}

main().catch((error) => {
  console.error(error instanceof Error ? error.message : error);
  process.exit(1);
});
