import assert from "node:assert/strict";
import { test, mock } from "node:test";
import { eq, sql } from "drizzle-orm";
import { accounts, assetClasses, assets, expenseCategories, journalEntries, users, userFxSettings, userSetupState } from "../src/db/schema";
import { D } from "../src/domain/decimal";
import { todayIso } from "../src/lib/format";

let cookie: string | null = null;
mock.module("next/headers", { namedExports: { cookies: async () => ({ get: () => cookie ? { value: cookie } : undefined, set: () => {} }), headers: async () => new Headers() } });
mock.module("next/cache", { namedExports: { revalidatePath: () => {} } });

test("bank review writes one balanced, reviewed, tenant-owned entry only after confirmation; replays survive FX changes", async () => {
  const { db } = await import("../src/db");
  const { createSchemaIfNotExists } = await import("../src/db/init-schema");
  const { createSession } = await import("../src/lib/auth");
  const { ensureCategoryCatalog, listCategoryTree } = await import("../src/features/categories/service");
  const { confirmBankImportAction } = await import("../src/app/actions/bankImport");
  await createSchemaIfNotExists();
  await ensureCategoryCatalog();
  const [owner] = await db.insert(users).values({ name: "Reviewer", username: "reviewer", role: "user" }).returning();
  const [other] = await db.insert(users).values({ name: "Other", username: "other-reviewer", role: "user" }).returning();
  const [cash] = await db.insert(assetClasses).values({ code: "cash", name: "نقد و بانک" }).returning();
  await db.insert(assets).values({ symbol: "USD", name: "دلار", classId: cash.id, decimals: 2 });
  const [irt] = await db.insert(assets).values({ symbol: "IRT", name: "تومان", classId: cash.id, decimals: 0 }).returning();
  const [bank] = await db.insert(accounts).values({ userId: owner.id, code: "1010", name: "بانک", type: "asset", assetId: irt.id }).returning();
  const [foreign] = await db.insert(accounts).values({ userId: other.id, code: "1010", name: "بانک دیگری", type: "asset", assetId: irt.id }).returning();
  await db.insert(accounts).values({ userId: owner.id, code: "5900", name: "هزینه", type: "expense", assetId: irt.id });
  await db.insert(accounts).values({ userId: owner.id, code: "4010", name: "درآمد", type: "income", assetId: irt.id });
  await db.insert(userFxSettings).values({ userId: owner.id, currentRate: "100000" });
  const leaf = (await listCategoryTree(owner.id)).flatMap((g) => g.children).find((c) => c.code === "FOD-GROCERY-HOME")!;
  const incomeLeaf = (await listCategoryTree(owner.id, "income")).flatMap((g) => g.children)[0];
  const fd = (fields: Record<string, string> = {}) => {
    const form = new FormData();
    Object.entries({ source: "برداشت 250000 تومان 1405/06/26", type: "expense", accountId: bank.id, categoryId: leaf.id, amountToman: "250000", date: todayIso(), description: "خرید مواد غذایی", confirmed: "yes", rateConfirmed: "yes", expectedRate: "100000", ...fields }).forEach(([k, v]) => form.set(k, v));
    return form;
  };
  assert.equal((await confirmBankImportAction(fd())).ok, false, "anonymous requests cannot post");
  cookie = (await createSession(owner.id)).token;
  assert.equal((await confirmBankImportAction(fd())).ok, false, "onboarding is required before posting");
  await db.insert(userSetupState).values({ userId: owner.id, completed: true, currentStep: 7 });
  assert.equal((await confirmBankImportAction(fd({ confirmed: "no" }))).ok, false);
  assert.equal((await confirmBankImportAction(fd({ rateConfirmed: "no" }))).ok, false);
  assert.equal((await confirmBankImportAction(fd({ categoryId: "" }))).ok, false);
  assert.equal((await confirmBankImportAction(fd({ categoryId: incomeLeaf.id }))).ok, false);
  assert.equal((await confirmBankImportAction(fd({ accountId: foreign.id }))).ok, false);
  assert.equal((await confirmBankImportAction(fd({ date: "2026-02-30" }))).ok, false);
  await db.update(expenseCategories).set({ isActive: false }).where(eq(expenseCategories.id, leaf.id));
  assert.equal((await confirmBankImportAction(fd())).ok, false, "inactive categories cannot post");
  await db.update(expenseCategories).set({ isActive: true }).where(eq(expenseCategories.id, leaf.id));
  assert.equal((await db.select().from(journalEntries)).length, 0);
  const posted = await confirmBankImportAction(fd());
  assert.equal(posted.ok, true, posted.message);
  assert.ok(posted.entryId);
  const [entry] = await db.select().from(journalEntries).where(eq(journalEntries.id, posted.entryId!));
  assert.equal(entry.userId, owner.id);
  assert.equal(entry.source, "import");
  assert.match(entry.reference!, /^bank-import:[a-f0-9]{64}$/);
  const integrity = await db.execute(sql`select sum(base_value)::text as delta, count(*)::int as n from postings where entry_id = ${entry.id}`);
  assert.equal(D(integrity.rows[0].delta as string).toString(), "0");
  assert.equal(integrity.rows[0].n, 2);
  const review = await db.execute(sql`select entry_id from entry_reviews where entry_id = ${entry.id}`);
  assert.equal(review.rows.length, 1);
  await db.update(userFxSettings).set({ currentRate: "200000" }).where(eq(userFxSettings.userId, owner.id));
  const { invalidateUserFxRateCache } = await import("../src/features/fx/userRate");
  invalidateUserFxRateCache(owner.id);
  assert.equal((await confirmBankImportAction(fd())).entryId, entry.id);
  assert.equal((await db.select().from(journalEntries)).length, 1, "same source posts once after FX changes");
  assert.equal((await confirmBankImportAction(fd({ source: "پیام دیگر با همین مبلغ" }))).duplicate, true);
  assert.equal((await db.select().from(journalEntries)).length, 1, "similar posting requires explicit separate review");
  const snapshot = await db.execute(sql`select fx_rate::text from entry_fx_snapshots where entry_id = ${entry.id}`);
  assert.equal(D(snapshot.rows[0].fx_rate as string).toString(), "100000", "historical freeze remains intact");

  assert.equal((await confirmBankImportAction(fd({ source: "واریز حقوق 500000 تومان", type: "income", categoryId: incomeLeaf.id, amountToman: "500000", description: "حقوق" }))).ok, false, "a stale FX confirmation cannot post");
  const salary = await confirmBankImportAction(fd({ source: "واریز حقوق 1000000 تومان", type: "income", categoryId: incomeLeaf.id, amountToman: "1000000", description: "حقوق", expectedRate: "200000" }));
  assert.equal(salary.ok, true, salary.message);
  const [destination] = await db.insert(accounts).values({ userId: owner.id, code: "1020", name: "بانک مقصد", type: "asset", assetId: irt.id }).returning();
  const transfer = await confirmBankImportAction(fd({ source: "انتقال به بانک مقصد 100000 تومان", type: "transfer", destinationId: destination.id, amountToman: "100000", description: "انتقال شخصی", expectedRate: "200000" }));
  assert.equal(transfer.ok, true, transfer.message);
  const [transferEntry] = await db.select().from(journalEntries).where(eq(journalEntries.id, transfer.entryId!));
  assert.equal(transferEntry.type, "transfer");
  assert.equal(transferEntry.source, "import");
  assert.equal(transferEntry.categoryId, null, "transfers never acquire an expense category");
  const secondSide = await confirmBankImportAction(fd({ source: "واریز از بانک مبدأ 100000 تومان", type: "income", accountId: destination.id, categoryId: incomeLeaf.id, amountToman: "100000", description: "دریافت انتقال" }));
  assert.equal(secondSide.duplicate, true, "the credit side of an existing transfer is detected");
  const concurrent = await Promise.all([1, 2].map(() => confirmBankImportAction(fd({ source: "واریز 700000 تومان برای تست همزمان", type: "income", categoryId: incomeLeaf.id, amountToman: "700000", description: "درآمد مستقل", expectedRate: "200000" }))));
  assert.ok(concurrent.every((r) => r.ok), JSON.stringify(concurrent));
  assert.equal(concurrent[0].entryId, concurrent[1].entryId);
  assert.equal((await db.select().from(journalEntries)).length, 4, "concurrent confirmations cannot duplicate the source");
});
