import assert from "node:assert/strict";
import { mock, test } from "node:test";
import { eq, sql } from "drizzle-orm";
import { accounts, assetClasses, assets, bankSmsConnections, bankSmsInbox, bankSmsIdentifiers, journalEntries, postings, users, userFxSettings, userSetupState } from "../src/db/schema";
import { todayIso } from "../src/lib/format";
let cookie: string | null = null;
mock.module("next/headers", { namedExports: { cookies: async () => ({ get: () => cookie ? { value: cookie } : undefined, set: () => {} }), headers: async () => new Headers() } });
mock.module("next/cache", { namedExports: { revalidatePath: () => {} } });

test("iPhone SMS: setup, write-only credentials, encrypted tenant inbox, retries, explicit review, deletion and revocation", async () => {
  process.env.FIELD_ENCRYPTION_KEY = Buffer.alloc(32, 7).toString("base64");
  process.env.NEXT_PUBLIC_SITE_URL = "https://example.test";
  const { db } = await import("../src/db");
  const { createSchemaIfNotExists } = await import("../src/db/init-schema");
  const { createSession } = await import("../src/lib/auth");
  const { createSmsConnection, listSmsDrafts, hashSmsToken } = await import("../src/features/bankImport/sms");
  const { POST } = await import("../src/app/api/bank-messages/route");
  const { confirmBankImportAction } = await import("../src/app/actions/bankImport");
  const { createIphoneConnectionAction, revokeIphoneConnectionAction, rejectBankSmsAction } = await import("../src/app/actions/bankSms");
  const { ensureCategoryCatalog, listCategoryTree } = await import("../src/features/categories/service");
  await createSchemaIfNotExists();
  await createSchemaIfNotExists(); // initializer remains idempotent
  await ensureCategoryCatalog();
  const [owner] = await db.insert(users).values({ name: "iPhone owner", role: "user", username: "iphone-owner" }).returning();
  const [other] = await db.insert(users).values({ name: "Other", role: "user", username: "iphone-other" }).returning();
  await assert.rejects(() => createSmsConnection(owner.id, "iPhone"), /SETUP_REQUIRED/);
  await db.insert(userSetupState).values({ userId: owner.id, completed: true, currentStep: 7 });
  const [cash] = await db.insert(assetClasses).values({ code: "cash", name: "نقد و بانک" }).returning();
  await db.insert(assets).values({ symbol: "USD", name: "دلار", classId: cash.id, decimals: 2 });
  const [irt] = await db.insert(assets).values({ symbol: "IRT", name: "تومان", classId: cash.id, decimals: 0 }).returning();
  const [bank] = await db.insert(accounts).values({ userId: owner.id, code: "1010", name: "بانک", type: "asset", assetId: irt.id }).returning();
  await db.insert(accounts).values({ userId: owner.id, code: "5900", name: "هزینه", type: "expense", assetId: irt.id });
  await db.insert(userFxSettings).values({ userId: owner.id, currentRate: "100000" });
  cookie = (await createSession(owner.id)).token;
  assert.equal((await createIphoneConnectionAction({ name: "iPhone", consent: false })).ok, false);
  delete process.env.FIELD_ENCRYPTION_KEY;
  await assert.rejects(() => createSmsConnection(owner.id, "iPhone"), /encryption/);
  process.env.FIELD_ENCRYPTION_KEY = Buffer.alloc(32, 7).toString("base64");
  const connection = await createSmsConnection(owner.id, "iPhone");
  const [storedConnection] = await db.select().from(bankSmsConnections);
  assert.equal(storedConnection.tokenHash, hashSmsToken(connection.token));
  assert.ok(!JSON.stringify(storedConnection).includes(connection.token));
  const input = { message: "بانک ملت برداشت: 250000 تومان", sender: "بانک ملت", sentAt: new Date(Date.now() + 1000).toISOString() };
  const post = (body: unknown, token = connection.token, contentType = "application/json") => POST(new Request("https://example.test/api/bank-messages", { method: "POST", headers: { Authorization: `Bearer ${token}`, "Content-Type": contentType }, body: JSON.stringify(body) }));
  assert.equal((await post(input, "invalid")).status, 401);
  assert.equal((await post(input, connection.token, "text/plain")).status, 415);
  assert.equal((await post({ ...input, userId: other.id })).status, 400);
  assert.equal((await post({ ...input, sentAt: "not-a-date" })).status, 400);
  assert.equal((await post({ ...input, message: "رمز یکبار مصرف: 123456" })).status, 422);
  assert.equal((await post({ ...input, message: "برداشت 200 تومان 1400/01/01" })).status, 422);
  assert.equal((await post({ ...input, sentAt: new Date(connection.createdAt.getTime() - 1000).toISOString() })).status, 422);
  assert.equal((await post({ ...input, message: "a".repeat(40000) })).status, 413);
  const firstReceipts = await Promise.all([post(input), post(input)]);
  assert.ok(firstReceipts.every((r) => r.status === 202));
  assert.deepEqual((await Promise.all(firstReceipts.map((r) => r.json()))).map((r) => r.duplicate).sort(), [false, true]);
  const replay = await post(input);
  assert.equal((await replay.json()).duplicate, true);
  const rows = await db.select().from(bankSmsInbox);
  assert.equal(rows.length, 1);
  assert.match(rows[0].encryptedPayload!, /^enc:v1:/);
  assert.ok(!rows[0].encryptedPayload!.includes(input.message));
  assert.equal((await listSmsDrafts(other.id)).length, 0);
  const drafts = await listSmsDrafts(owner.id);
  assert.equal(drafts[0].source, input.message);
  assert.equal(drafts[0].amountToman, "250000");
  assert.equal((await db.select().from(journalEntries)).length, 0, "receipt must never post to the ledger");
  const leaf = (await listCategoryTree(owner.id)).flatMap((g) => g.children).find((c) => c.code === "FOD-GROCERY-HOME")!;
  const fd = (fields: Record<string, string> = {}) => {
    const form = new FormData();
    Object.entries({ inboxId: rows[0].id, source: input.message, type: "expense", accountId: bank.id, categoryId: leaf.id, amountToman: "250000", date: todayIso(), description: "مواد غذایی", confirmed: "yes", rateConfirmed: "yes", expectedRate: "100000", openingConfirmed: "yes", ...fields }).forEach(([k, v]) => form.set(k, v));
    return form;
  };
  assert.equal((await confirmBankImportAction(fd({ openingConfirmed: "no" }))).ok, false);
  assert.equal((await confirmBankImportAction(fd({ confirmed: "no" }))).ok, false);
  cookie = (await createSession(other.id)).token;
  assert.equal((await revokeIphoneConnectionAction(connection.id)).ok, false);
  assert.equal((await rejectBankSmsAction(rows[0].id)).ok, false);
  assert.equal((await confirmBankImportAction(fd())).ok, false);
  cookie = (await createSession(owner.id)).token;
  const result = await confirmBankImportAction(fd());
  assert.equal(result.ok, true, result.message);
  assert.equal((await confirmBankImportAction(fd())).entryId, result.entryId);
  const [confirmed] = await db.select().from(bankSmsInbox).where(eq(bankSmsInbox.id, rows[0].id));
  assert.equal(confirmed.status, "confirmed");
  assert.equal(confirmed.encryptedPayload, null);
  assert.equal((await db.select().from(journalEntries)).length, 1);
  assert.equal((await post({ ...input, message: "واریز 60000 تومان" })).status, 202);
  const [pending] = await listSmsDrafts(owner.id);
  assert.equal((await rejectBankSmsAction(pending.inboxId)).ok, true);
  assert.equal((await listSmsDrafts(owner.id)).length, 0);
  const [rejected] = await db.select().from(bankSmsInbox).where(eq(bankSmsInbox.id, pending.inboxId));
  assert.equal(rejected.encryptedPayload, null);
  const { addBankIdentifierAction, removeBankIdentifierAction } = await import("../src/app/actions/bankIdentifiers");
  const { listBankIdentifiers } = await import("../src/features/bankImport/identifiers");
  const { default: SetupMessagesPage } = await import("../src/app/setup/messages/page");
  assert.equal((await addBankIdentifierAction({ accountId: bank.id, bankName: "بانک ملت", kind: "card", suffix: "۱۲۳۴" })).ok, true);
  assert.equal((await addBankIdentifierAction({ accountId: bank.id, bankName: "ملت", kind: "card", suffix: "6037991234561234" })).ok, false);
  const beforeSetupPage = await db.select().from(journalEntries);
  const setupPage = await SetupMessagesPage();
  const setupChildren = setupPage.props.children as { type?: { name?: string }; props?: { identifiers?: { accountId: string }[]; accounts?: { id: string }[]; connections?: { id: string; token?: string; tokenHash?: string }[] } }[];
  const mappingPanel = setupChildren.find((child) => child.type?.name === "BankIdentifiers")!;
  assert.ok(mappingPanel.props!.accounts!.every((account) => account.id === bank.id));
  assert.ok(mappingPanel.props!.identifiers!.every((identifier) => identifier.accountId === bank.id));
  const connectionPanel = setupChildren.find((child) => child.type?.name === "IphoneSmsConnection")!;
  assert.equal(connectionPanel.props!.connections![0].id, connection.id);
  assert.equal(connectionPanel.props!.connections![0].token, undefined);
  assert.equal(connectionPanel.props!.connections![0].tokenHash, undefined);
  assert.deepEqual(await db.select().from(journalEntries), beforeSetupPage, "reopening SMS setup never repeats opening entries");
  const [identifier] = await listBankIdentifiers(owner.id);
  assert.equal(identifier.suffix, "1234");
  assert.equal((await listBankIdentifiers(other.id)).length, 0);
  await db.insert(userSetupState).values({ userId: other.id, completed: true, currentStep: 7 });
  cookie = (await createSession(other.id)).token;
  assert.equal((await addBankIdentifierAction({ accountId: bank.id, bankName: "ملت", kind: "card", suffix: "5678" })).ok, false);
  assert.equal((await removeBankIdentifierAction(identifier.id)).ok, false);
  cookie = (await createSession(owner.id)).token;
  assert.equal((await db.select().from(bankSmsIdentifiers)).length, 1);
  assert.equal((await post({ ...input, message: "بانک ملت کارت: ****1234 برداشت: 100 تومان" })).status, 202);
  const [transferSms] = await listSmsDrafts(owner.id);
  assert.equal(transferSms.suggestedAccountId, bank.id);
  const [destination] = await db.insert(accounts).values({ userId: owner.id, code: "1011", name: "بانک دوم", type: "asset", assetId: irt.id }).returning();
  // Fixture represents an already reviewed transfer, not a second financial event.
  const [transfer] = await db.insert(journalEntries).values({ userId: owner.id, entryDate: todayIso(), type: "transfer", description: "انتقال بین دو حساب" }).returning();
  await db.insert(postings).values([
    { entryId: transfer.id, accountId: bank.id, assetId: irt.id, quantity: "-100", baseValue: "-0.001" },
    { entryId: transfer.id, accountId: destination.id, assetId: irt.id, quantity: "100", baseValue: "0.001" },
  ]);
  const transferForm = (overrides: Record<string, string> = {}) => fd({ inboxId: transferSms.inboxId, source: transferSms.source, type: "transfer", destinationId: destination.id, amountToman: "100", ...overrides });
  const candidate = await confirmBankImportAction(transferForm());
  assert.equal(candidate.ok, false);
  assert.equal(candidate.transferEntryId, transfer.id);
  const beforeLink = await db.select().from(postings);
  assert.equal((await confirmBankImportAction(transferForm({ existingTransferId: result.entryId! }))).ok, false, "an expense is not a transfer");
  assert.equal((await confirmBankImportAction(transferForm({ existingTransferId: transfer.id, amountToman: "101" }))).ok, false);
  assert.equal((await confirmBankImportAction(transferForm({ existingTransferId: transfer.id, accountId: destination.id, destinationId: bank.id }))).ok, false, "source and destination cannot be reversed");
  cookie = (await createSession(other.id)).token;
  assert.equal((await confirmBankImportAction(transferForm({ existingTransferId: transfer.id }))).ok, false);
  cookie = (await createSession(owner.id)).token;
  const links = await Promise.all([confirmBankImportAction(transferForm({ existingTransferId: transfer.id })), confirmBankImportAction(transferForm({ existingTransferId: transfer.id }))]);
  assert.ok(links.every((link) => link.ok && link.entryId === transfer.id));
  assert.deepEqual(await db.select().from(postings), beforeLink, "linking must not change ledger postings");
  assert.equal((await db.select().from(journalEntries)).length, 2);
  const [linkedSms] = await db.select().from(bankSmsInbox).where(eq(bankSmsInbox.id, transferSms.inboxId));
  assert.equal(linkedSms.entryId, transfer.id);
  assert.equal(linkedSms.encryptedPayload, null);
  assert.equal((await removeBankIdentifierAction(identifier.id)).ok, true);
  await db.update(userSetupState).set({ completed: false }).where(eq(userSetupState.userId, owner.id));
  assert.equal((await post({ ...input, message: "واریز 1000 تومان" })).status, 403);
  await assert.rejects(() => SetupMessagesPage(), /NEXT_REDIRECT/, "SMS onboarding requires completed financial setup even for existing accounts");
  await db.update(userSetupState).set({ completed: true }).where(eq(userSetupState.userId, owner.id));
  assert.equal((await revokeIphoneConnectionAction(connection.id)).ok, true);
  assert.equal((await post(input)).status, 401);
  const security = await db.execute(sql`select relname, relrowsecurity from pg_class where relname in ('bank_sms_inbox','bank_sms_connections','bank_sms_identifiers')`);
  assert.ok(security.rows.every((r) => r.relrowsecurity === true));
  await db.execute(sql`create role sms_untrusted nologin`);
  const denied = await db.execute(sql`select has_table_privilege('sms_untrusted','bank_sms_inbox','select,insert,update,delete') as inbox, has_table_privilege('sms_untrusted','bank_sms_connections','select,insert,update,delete') as credentials, has_table_privilege('sms_untrusted','bank_sms_identifiers','select,insert,update,delete') as identifiers`);
  assert.equal(denied.rows[0].inbox, false);
  assert.equal(denied.rows[0].credentials, false);
  assert.equal(denied.rows[0].identifiers, false);
});
