/**
 * دارایی واقعی → ملک (Real Estate module)
 *
 * These tests lock down the non-negotiable rules of the real estate module:
 *
 *   1. City / neighborhood / property type come ONLY from active master data —
 *      free text is rejected (no name/symbol/city/area/type typed by users).
 *   2. Asset name AND symbol are generated by the system; symbol is unique
 *      (RE-AHZ-KPE-APT-0001) and immutable.
 *   3. The user enters PERSIAN dates; the system stores Gregorian/ISO and the
 *      Persian display copy (never two independent contradicting dates).
 *   4. Purchase USD = purchase Toman ÷ FX rate OF THE ACQUISITION DATE
 *      (never today's rate); Current USD = current Toman ÷ FX rate OF THE
 *      VALUATION DATE. Both rates are frozen and auditable.
 *   5. A property bought BEFORE the system existed is a PRIOR-PERIOD
 *      ACQUISITION: the ledger entry is dated at the REAL acquisition date,
 *      credits Opening Equity, and NEVER creates a cash outflow at the
 *      system-entry date.
 *   6. Historical transactions are immutable: a revaluation updates only the
 *      current value (+ prices row), never the ledger entry.
 *   7. The current value automatically enters the aggregates (real-asset
 *      totals AND net worth), in USD at the valuation-date rate.
 *   8. Master data is extensible: admins can add/rename/deactivate
 *      cities, neighborhoods and property types; inactive entries are not
 *      selectable by normal users.
 */
import assert from "node:assert/strict";
import { test } from "node:test";
import { eq, sql } from "drizzle-orm";
import { db } from "../src/db";
import { createSchemaIfNotExists } from "../src/db/init-schema";
import {
  accounts,
  assets,
  exchangeRates,
  journalEntries,
  postings,
  prices,
  realEstateProperties,
  cities,
  neighborhoods,
  propertyTypes,
} from "../src/db/schema";
import {
  createRealEstateAsset,
  listRealEstateAssets,
  previewRealEstateIdentity,
  recordRealEstateValuation,
  computePerformance,
  buildAssetName,
  buildSymbol,
} from "../src/features/rwa/realEstate/service";
import {
  createNeighborhood,
  listNeighborhoods,
  listPropertyTypes,
  setNeighborhoodActive,
  seedRealEstateMasterData,
} from "../src/features/rwa/realEstate/masterData";
import { getNetWorth } from "../src/features/ledger/queries";
import { jalaliToIso } from "../src/lib/format";
import { D } from "../src/domain/decimal";

/* 1404/05/20 → 2025-08-11 ; 1405/05/20 → 2026-08-11 (today in the sandbox) */
const ACQUISITION = jalaliToIso(1404, 5, 20);
const VALUATION = jalaliToIso(1405, 5, 20);
const PURCHASE_TOMAN = "4500000000";
const CURRENT_TOMAN = "7000000000";

async function reset() {
  await createSchemaIfNotExists();
  await db.delete(realEstateProperties);
  await db.delete(prices);
  await db.delete(postings);
  await db.delete(journalEntries);
  await db.delete(exchangeRates);
  // Re-seed master data from scratch (fresh in-memory DB per test file).
  await db.delete(neighborhoods);
  await db.delete(propertyTypes);
  await db.delete(cities);
  await seedRealEstateMasterData();
}

async function setFxRate(date: string, rate: string) {
  await db
    .insert(exchangeRates)
    .values({ baseCurrency: "USD", quoteCurrency: "IRT", effectiveDate: date, rate, source: "test" })
    .onConflictDoNothing();
}

async function pickAhvazKianparsEastApartment() {
  const cityRows = await db.select().from(cities).where(eq(cities.code, "AHZ"));
  assert.ok(cityRows[0], "Ahvaz city must be seeded");
  const hoodRows = await db.select().from(neighborhoods).where(eq(neighborhoods.code, "KPE"));
  assert.ok(hoodRows[0], "Kianpars East must be seeded");
  const typeRows = await db.select().from(propertyTypes).where(eq(propertyTypes.code, "APT"));
  assert.ok(typeRows[0], "Apartment type must be seeded");
  return { cityId: cityRows[0]!.id, neighborhoodId: hoodRows[0]!.id, propertyTypeId: typeRows[0]!.id };
}

async function ledgerEntryOf(propertyId: string) {
  const [row] = await db
    .select({ entryId: realEstateProperties.ledgerEntryId })
    .from(realEstateProperties)
    .where(eq(realEstateProperties.id, propertyId))
    .limit(1);
  return row?.entryId ?? null;
}

/* ─────────────────────────── master data ─────────────────────────── */

test("master data seeds Ahvaz, its 16 neighborhoods and 12 property types", async () => {
  await reset();
  const cityRows = await db.select().from(cities);
  assert.equal(cityRows.length, 1);
  assert.equal(cityRows[0]!.code, "AHZ");
  assert.equal(cityRows[0]!.nameFa, "اهواز");

  const hoods = await listNeighborhoods(cityRows[0]!.id);
  assert.equal(hoods.length, 16, "all 16 Ahvaz neighborhoods must be seeded");
  const hoodCodes = hoods.map((h) => h.code);
  for (const code of ["GOL", "SAD", "FAR", "BAG", "AMA", "KUR", "KNO", "KPE", "KPW", "SDU", "ZKA", "KAE", "KAW", "PAD", "ARS", "MHR"]) {
    assert.ok(hoodCodes.includes(code), `neighborhood ${code} missing`);
  }

  const types = await listPropertyTypes();
  assert.equal(types.length, 12, "all 12 property types must be seeded");
  const typeCodes = types.map((t) => t.code);
  for (const code of ["APT", "HOU", "LND", "SHO", "OFF", "VIL", "GAR", "ADM", "IND", "WAR", "PRK", "OTH"]) {
    assert.ok(typeCodes.includes(code), `property type ${code} missing`);
  }
});

test("master data is extensible: add + deactivate + rename a neighborhood", async () => {
  await reset();
  const cityRows = await db.select().from(cities).where(eq(cities.code, "AHZ"));
  const hood = await createNeighborhood({ cityId: cityRows[0]!.id, nameFa: "محله آزمایشی", nameEn: "Test Hood", code: "TST" });
  assert.ok(hood.id);

  // Deactivated → hidden from normal users, still present for admins.
  await setNeighborhoodActive(hood.id, false);
  const active = await listNeighborhoods(cityRows[0]!.id);
  assert.ok(!active.some((h) => h.id === hood.id), "inactive neighborhood must not be listed for users");
  const all = await listNeighborhoods(cityRows[0]!.id, true);
  assert.ok(all.some((h) => h.id === hood.id), "inactive neighborhood must still exist for admins");
});

/* ─────────────────────── name & symbol ─────────────────────── */

test("name and symbol are generated: RE-AHZ-KPE-APT-0001 pattern, sequence for duplicates", async () => {
  await reset();
  const ids = await pickAhvazKianparsEastApartment();
  await setFxRate(ACQUISITION, "100000");
  await setFxRate(VALUATION, "100000");

  const first = await createRealEstateAsset({
    cityId: ids.cityId,
    neighborhoodId: ids.neighborhoodId,
    propertyTypeId: ids.propertyTypeId,
    acquisitionDate: ACQUISITION,
    acquisitionDatePersian: "1404/05/20",
    valuationDate: VALUATION,
    valuationDatePersian: "1405/05/20",
    purchasePriceToman: PURCHASE_TOMAN,
    currentValueToman: CURRENT_TOMAN,
  });
  assert.equal(first.symbol, "RE-AHZ-KPE-APT-0001");
  assert.equal(first.assetName, "آپارتمان — اهواز — کیانپارس شرقی");

  // Same area + same type → sequential suffix and next symbol.
  const second = await createRealEstateAsset({
    cityId: ids.cityId,
    neighborhoodId: ids.neighborhoodId,
    propertyTypeId: ids.propertyTypeId,
    acquisitionDate: ACQUISITION,
    acquisitionDatePersian: "1404/05/20",
    valuationDate: VALUATION,
    valuationDatePersian: "1405/05/20",
    purchasePriceToman: PURCHASE_TOMAN,
    currentValueToman: CURRENT_TOMAN,
  });
  assert.equal(second.symbol, "RE-AHZ-KPE-APT-0002");
  assert.equal(second.assetName, "آپارتمان — اهواز — کیانپارس شرقی — 002");

  // Symbols are unique in the assets table (DB unique constraint).
  const symbols = await db.select({ s: assets.symbol }).from(assets).where(sql`symbol like 'RE-%'`);
  assert.equal(new Set(symbols.map((r) => r.s)).size, symbols.length, "symbols must be unique");

  // Preview returns the same generated values.
  const preview = await previewRealEstateIdentity(ids.cityId, ids.neighborhoodId, ids.propertyTypeId);
  assert.equal(preview?.symbol, "RE-AHZ-KPE-APT-0003");
  assert.equal(preview?.assetName, "آپارتمان — اهواز — کیانپارس شرقی — 003");
});

test("users cannot supply a name or symbol — the service ignores/derives them", async () => {
  await reset();
  const ids = await pickAhvazKianparsEastApartment();
  await setFxRate(ACQUISITION, "100000");
  await setFxRate(VALUATION, "100000");
  const result = await createRealEstateAsset({
    cityId: ids.cityId,
    neighborhoodId: ids.neighborhoodId,
    propertyTypeId: ids.propertyTypeId,
    acquisitionDate: ACQUISITION,
    valuationDate: VALUATION,
    purchasePriceToman: PURCHASE_TOMAN,
    currentValueToman: CURRENT_TOMAN,
  });
  // Generated, not "MY-PROPERTY" or anything user-typed.
  assert.match(result.symbol, /^RE-[A-Z]{3}-[A-Z]{3}-[A-Z]{3}-\d{4}$/);
  assert.equal(result.assetName, "آپارتمان — اهواز — کیانپارس شرقی");
});

/* ─────────────────────── historical FX ─────────────────────── */

test("purchase USD uses the ACQUISITION-date rate; current USD uses the VALUATION-date rate", async () => {
  await reset();
  const ids = await pickAhvazKianparsEastApartment();
  await setFxRate(ACQUISITION, "90000"); // 1404/05/20
  await setFxRate(VALUATION, "150000"); // 1405/05/20
  // A "today" rate that must NEVER be used:
  await setFxRate("2026-08-11", "999999");

  const result = await createRealEstateAsset({
    cityId: ids.cityId,
    neighborhoodId: ids.neighborhoodId,
    propertyTypeId: ids.propertyTypeId,
    acquisitionDate: ACQUISITION,
    acquisitionDatePersian: "1404/05/20",
    valuationDate: VALUATION,
    valuationDatePersian: "1405/05/20",
    purchasePriceToman: PURCHASE_TOMAN,
    currentValueToman: CURRENT_TOMAN,
  });

  const assetsList = await listRealEstateAssets();
  const asset = assetsList.find((a) => a.id === result.id);
  assert.ok(asset, "property must appear in the asset list");

  assert.equal(asset!.purchaseFxRate, "90000");
  assert.equal(asset!.purchaseFxRateDate, ACQUISITION);
  assert.equal(asset!.purchaseFxRateSource, "exact");
  // 4,500,000,000 ÷ 90,000 = 50,000 USD
  assert.equal(asset!.purchaseValueUsd, "50000.00");

  assert.equal(asset!.valuationFxRate, "150000");
  assert.equal(asset!.valuationFxRateDate, VALUATION);
  assert.equal(asset!.valuationFxRateSource, "exact");
  // 7,000,000,000 ÷ 150,000 = 46,666.67 USD
  assert.equal(asset!.currentValueUsd, "46666.67");

  // Neither amount was computed with today's 999,999 rate.
  // (If today's rate had been used, 7B ÷ 999,999 ≈ 7,000 USD — nowhere near 46,666.)
  assert.ok(!asset!.purchaseValueUsd?.startsWith("4500"));
  assert.ok(Number(asset!.currentValueUsd) > 10000, "must not use today's rate");
});

test("rates are frozen: a later FX change never rewrites stored values", async () => {
  await reset();
  const ids = await pickAhvazKianparsEastApartment();
  await setFxRate(ACQUISITION, "80000");
  await setFxRate(VALUATION, "80000");

  const result = await createRealEstateAsset({
    cityId: ids.cityId,
    neighborhoodId: ids.neighborhoodId,
    propertyTypeId: ids.propertyTypeId,
    acquisitionDate: ACQUISITION,
    acquisitionDatePersian: "1404/05/20",
    valuationDate: VALUATION,
    valuationDatePersian: "1405/05/20",
    purchasePriceToman: PURCHASE_TOMAN,
    currentValueToman: CURRENT_TOMAN,
  });

  // Insert a new "current" rate — the frozen values must not move.
  await setFxRate("2026-08-11", "500000");
  const after = await listRealEstateAssets();
  const asset = after.find((a) => a.id === result.id)!;
  assert.equal(asset.purchaseValueUsd, "56250.00"); // 4.5B ÷ 80k
  assert.equal(asset.currentValueUsd, "87500.00"); // 7B ÷ 80k
  assert.equal(asset.purchaseFxRate, "80000");
});

/* ─────────────────────── Persian → Gregorian ─────────────────────── */

test("Persian dates are converted to Gregorian/ISO and both are stored", async () => {
  await reset();
  const ids = await pickAhvazKianparsEastApartment();
  await setFxRate(ACQUISITION, "100000");
  await setFxRate(VALUATION, "100000");
  const result = await createRealEstateAsset({
    cityId: ids.cityId,
    neighborhoodId: ids.neighborhoodId,
    propertyTypeId: ids.propertyTypeId,
    acquisitionDate: ACQUISITION,
    acquisitionDatePersian: "1404/05/20",
    valuationDate: VALUATION,
    valuationDatePersian: "1405/05/20",
    purchasePriceToman: PURCHASE_TOMAN,
    currentValueToman: CURRENT_TOMAN,
  });
  const [row] = await db.select().from(realEstateProperties).where(eq(realEstateProperties.id, result.id));
  assert.equal(row!.acquisitionDate, "2025-08-11", "1404/05/20 must convert to 2025-08-11");
  assert.equal(row!.acquisitionDatePersian, "1404/05/20");
  assert.equal(row!.valuationDate, "2026-08-11", "1405/05/20 must convert to 2026-08-11");
  assert.equal(row!.valuationDatePersian, "1405/05/20");
});

/* ─────────────────────── P&L (derived, dual-currency) ─────────────────────── */

test("Toman and USD P&L are computed independently and correctly", async () => {
  const perf = computePerformance("4500000000", "7000000000", "50000.00", "46666.67");
  assert.equal(perf.gainToman, "2500000000");
  assert.equal(perf.roiToman, "55.56");
  // USD went DOWN: +2500M toman profit but negative USD P&L.
  assert.equal(perf.gainUsd, "-3333.33");
  assert.ok(Number(perf.roiUsd!) < 0);
});

/* ─────────────────────── ledger integration ─────────────────────── */

test("prior-period acquisition posts an OPENING entry dated at the acquisition date — no cash outflow today", async () => {
  await reset();
  const ids = await pickAhvazKianparsEastApartment();
  await setFxRate(ACQUISITION, "90000");
  await setFxRate(VALUATION, "90000");

  const result = await createRealEstateAsset({
    cityId: ids.cityId,
    neighborhoodId: ids.neighborhoodId,
    propertyTypeId: ids.propertyTypeId,
    acquisitionDate: ACQUISITION,
    acquisitionDatePersian: "1404/05/20",
    valuationDate: VALUATION,
    valuationDatePersian: "1405/05/20",
    purchasePriceToman: PURCHASE_TOMAN,
    currentValueToman: CURRENT_TOMAN,
  });

  const entryId = await ledgerEntryOf(result.id);
  assert.ok(entryId, "asset ↔ ledger link must be stored");

  const [entry] = await db.select().from(journalEntries).where(eq(journalEntries.id, entryId!));
  assert.ok(entry, "ledger entry must exist");
  assert.equal(entry.entryDate, ACQUISITION, "entry must be dated at the REAL acquisition date");
  assert.equal(entry.type, "opening");
  assert.equal(entry.status, "posted");
  assert.match(entry.description, new RegExp(result.symbol));

  const lines = await db.select().from(postings).where(eq(postings.entryId, entryId!));
  assert.equal(lines.length, 2, "double-entry: exactly two postings");

  const accIds = lines.map((l) => l.accountId);
  const [assetAccount] = await db.select().from(accounts).where(eq(accounts.code, "1600"));
  const [equityAccount] = await db.select().from(accounts).where(eq(accounts.code, "3015"));
  assert.ok(assetAccount && equityAccount, "real-estate asset + opening equity accounts must exist");
  assert.ok(accIds.includes(assetAccount!.id), "Debit leg on the real-estate asset account");
  assert.ok(accIds.includes(equityAccount!.id), "Credit leg on opening equity — not cash");

  // Balanced: Σ base_value = 0 ; the debit leg carries the purchase USD value.
  const sumBase = lines.reduce((s, l) => s.add(D(l.baseValue)), D("0"));
  assert.equal(sumBase.toFixed(6), "0.000000", "entry must be balanced");
  const debit = lines.find((l) => D(l.baseValue).gt(0))!;
  assert.equal(D(debit.baseValue).toFixed(2), "50000.00", "debit = purchase USD at acquisition-date rate");

  // No cash outflow anywhere near the system entry date.
  const cashAccounts = await db
    .select({ id: accounts.id })
    .from(accounts)
    .where(sql`code in ('1010','1020','1030')`);
  const cashIds = cashAccounts.map((c) => c.id);
  assert.ok(!lines.some((l) => cashIds.includes(l.accountId)), "cash accounts must not be touched");
  const todayEntries = await db.select().from(journalEntries).where(sql`entry_date = current_date`);
  assert.equal(todayEntries.length, 0, "no entry may be dated at the system-entry date");
});

test("similar properties in one area get unique symbols and their own ledger entries", async () => {
  await reset();
  const ids = await pickAhvazKianparsEastApartment();
  await setFxRate(ACQUISITION, "100000");
  await setFxRate(VALUATION, "100000");
  const input = {
    cityId: ids.cityId,
    neighborhoodId: ids.neighborhoodId,
    propertyTypeId: ids.propertyTypeId,
    acquisitionDate: ACQUISITION,
    acquisitionDatePersian: "1404/05/20",
    valuationDate: VALUATION,
    valuationDatePersian: "1405/05/20",
    purchasePriceToman: PURCHASE_TOMAN,
    currentValueToman: CURRENT_TOMAN,
  };
  const a = await createRealEstateAsset(input);
  const b = await createRealEstateAsset(input);
  assert.notEqual(a.symbol, b.symbol, "each property must get a unique symbol");

  const entries = await db.select().from(journalEntries);
  assert.equal(entries.length, 2, "each property posts its own ledger entry");
  for (const e of entries) {
    assert.equal(e.type, "opening");
    assert.equal(e.entryDate, ACQUISITION);
    const lines = await db.select().from(postings).where(eq(postings.entryId, e.id));
    assert.equal(lines.length, 2);
    const sum = lines.reduce((s, l) => s.add(D(l.baseValue)), D("0"));
    assert.equal(sum.toFixed(6), "0.000000", "each entry balanced");
  }
});

/* ─────────────────────── revaluation & immutability ─────────────────────── */

test("a new valuation updates only the current value — the ledger entry stays untouched", async () => {
  await reset();
  const ids = await pickAhvazKianparsEastApartment();
  await setFxRate(ACQUISITION, "100000");
  await setFxRate(VALUATION, "100000");

  const result = await createRealEstateAsset({
    cityId: ids.cityId,
    neighborhoodId: ids.neighborhoodId,
    propertyTypeId: ids.propertyTypeId,
    acquisitionDate: ACQUISITION,
    acquisitionDatePersian: "1404/05/20",
    valuationDate: VALUATION,
    valuationDatePersian: "1405/05/20",
    purchasePriceToman: PURCHASE_TOMAN,
    currentValueToman: CURRENT_TOMAN,
  });
  const entryId = await ledgerEntryOf(result.id);
  const entryBefore = await db.select().from(journalEntries).where(eq(journalEntries.id, entryId!));
  const postingsBefore = await db.select().from(postings).where(eq(postings.entryId, entryId!));
  const [priceBefore] = await db.select().from(prices).where(eq(prices.assetId, result.assetId));

  const NEW_DATE = jalaliToIso(1405, 8, 1); // 2026-10-23
  await setFxRate(NEW_DATE, "120000");
  const reval = await recordRealEstateValuation({
    propertyId: result.id,
    valuationDate: NEW_DATE,
    valuationDatePersian: "1405/08/01",
    currentValueToman: "8400000000",
  });

  assert.equal(reval.currentValueToman, "8400000000");
  assert.equal(reval.currentValueUsd, "70000.00"); // 8.4B ÷ 120k
  assert.equal(reval.valuationFxRate, "120000");

  // Ledger untouched — immutable.
  const entryAfter = await db.select().from(journalEntries).where(eq(journalEntries.id, entryId!));
  const postingsAfter = await db.select().from(postings).where(eq(postings.entryId, entryId!));
  assert.deepEqual(entryAfter, entryBefore, "ledger entry must be immutable");
  assert.deepEqual(postingsAfter, postingsBefore, "postings must be immutable");

  // A NEW price row was appended (valuation-date rate), old one preserved.
  const priceRows = await db.select().from(prices).where(eq(prices.assetId, result.assetId)).orderBy(prices.asOf);
  assert.equal(priceRows.length, 2);
  assert.equal(priceRows[0]!.asOf, VALUATION, "first price row (original valuation) preserved");
  assert.equal(priceRows[1]!.asOf, NEW_DATE, "second price row dated at the new valuation date");
  assert.equal(D(priceRows[1]!.priceBase).toFixed(2), "70000.00"); // 8.4B ÷ 120k
  assert.ok(priceBefore, "first price row still exists");
});

/* ─────────────────────── aggregates / net worth ─────────────────────── */

test("current value enters the real-asset totals AND total net worth (USD at valuation-date rate)", async () => {
  await reset();
  const ids = await pickAhvazKianparsEastApartment();
  await setFxRate(ACQUISITION, "100000");
  await setFxRate(VALUATION, "100000");

  const result = await createRealEstateAsset({
    cityId: ids.cityId,
    neighborhoodId: ids.neighborhoodId,
    propertyTypeId: ids.propertyTypeId,
    acquisitionDate: ACQUISITION,
    acquisitionDatePersian: "1404/05/20",
    valuationDate: VALUATION,
    valuationDatePersian: "1405/05/20",
    purchasePriceToman: PURCHASE_TOMAN,
    currentValueToman: CURRENT_TOMAN,
  });

  const { getRealEstatePortfolioSummary } = await import("../src/features/rwa/realEstate/service");
  const summary = await getRealEstatePortfolioSummary();
  assert.equal(summary.count, 1);
  assert.equal(summary.totalCurrentToman, CURRENT_TOMAN);
  assert.equal(summary.totalCurrentUsd, "70000.00"); // 7B ÷ 100k
  assert.equal(summary.totalPurchaseToman, PURCHASE_TOMAN);
  assert.equal(summary.totalPurchaseUsd, "45000.00");
  assert.equal(summary.totalGainToman, "2500000000");
  assert.equal(summary.totalGainUsd, "25000.00");

  // Net worth (from the ledger + prices layer) includes the property at its
  // CURRENT value: qty 1 × latest price (current USD).
  const nw = await getNetWorth();
  const propHolding = nw.byClass.find((c) => c.className === "دارایی واقعی");
  assert.ok(propHolding, "real estate must appear in net-worth by class");
  assert.equal(Number(propHolding!.value).toFixed(2), "70000.00", "net worth must use the CURRENT valuation, not purchase cost");
  assert.equal(Number(nw.totalAssets).toFixed(2), "70000.00");
});

/* ─────────────────────── input validation ─────────────────────── */

test("inactive master data cannot be used to register a property", async () => {
  await reset();
  const ids = await pickAhvazKianparsEastApartment();

  const hoodRows = await db.select().from(neighborhoods).where(eq(neighborhoods.id, ids.neighborhoodId));
  await setNeighborhoodActive(hoodRows[0]!.id, false);

  await assert.rejects(
    () =>
      createRealEstateAsset({
        cityId: ids.cityId,
        neighborhoodId: ids.neighborhoodId,
        propertyTypeId: ids.propertyTypeId,
        acquisitionDate: ACQUISITION,
        valuationDate: VALUATION,
        purchasePriceToman: PURCHASE_TOMAN,
        currentValueToman: CURRENT_TOMAN,
      }),
    /غیرفعال|معتبر/i,
    "inactive neighborhood must be rejected",
  );
});

test("missing or non-positive amounts are rejected", async () => {
  await reset();
  const ids = await pickAhvazKianparsEastApartment();
  await setFxRate(ACQUISITION, "100000");
  await setFxRate(VALUATION, "100000");
  await assert.rejects(
    () =>
      createRealEstateAsset({
        cityId: ids.cityId,
        neighborhoodId: ids.neighborhoodId,
        propertyTypeId: ids.propertyTypeId,
        acquisitionDate: ACQUISITION,
        valuationDate: VALUATION,
        purchasePriceToman: "0",
        currentValueToman: CURRENT_TOMAN,
      }),
    /بزرگ‌تر از صفر/i,
  );
});

/* ─────────────────────── pure helpers ─────────────────────── */

test("buildAssetName / buildSymbol follow the spec examples", () => {
  const city = { id: "c", nameFa: "اهواز", nameEn: "Ahvaz", code: "AHZ", isActive: true, sortOrder: 0 } as any;
  const hood = { id: "h", cityId: "c", nameFa: "کیانپارس شرقی", nameEn: "Kianpars East", code: "KPE", isActive: true, sortOrder: 0 } as any;
  const apt = { id: "p", nameFa: "آپارتمان", nameEn: "Apartment", code: "APT", isActive: true, sortOrder: 0 } as any;

  assert.equal(buildAssetName(apt, city, hood, 1), "آپارتمان — اهواز — کیانپارس شرقی");
  assert.equal(buildAssetName(apt, city, hood, 7), "آپارتمان — اهواز — کیانپارس شرقی — 007");
  assert.equal(buildSymbol(apt, city, hood, 1), "RE-AHZ-KPE-APT-0001");
});
