/**
 * RWA Real Estate Service — دارایی واقعی → املاک / Real Estate
 *
 * The property is a fully ACCOUNTED asset:
 *
 *   • Identity comes 100% from master data — the user never types the city,
 *     neighborhood, property type, asset name or symbol.
 *   • Name  → «آپارتمان — اهواز — کیانپارس شرقی» (+ sequential suffix for
 *             similar properties in the same area), generated by the system.
 *   • Symbol→ a compact global RWA id (`001`, `002`, …), generated, unique
 *             (DB unique constraint on assets.symbol) and immutable.
 *   • Dates → the user enters PERSIAN dates; the UI converts to Gregorian/ISO
 *             which is the standard stored value (Persian kept for display).
 *   • FX    → purchase uses the rate OF THE ACQUISITION DATE, current value
 *             uses the rate OF THE VALUATION DATE. Both rates are frozen next
 *             to the amounts and are fully auditable (rate + source + date).
 *   • Ledger→ a double-entry OPENING entry dated at the REAL acquisition date
 *             (Debit: Real Estate Asset / Credit: Opening Equity). A property
 *             bought before the system started is a PRIOR-PERIOD ACQUISITION:
 *             no cash outflow is ever created at the system-entry date.
 *   • Current value is updated ONLY by a new valuation — it never rewrites the
 *     immutable purchase history or the ledger.
 */
import { and, asc, desc, eq, isNotNull, isNull, or, sql } from "drizzle-orm";
import { db } from "@/db";
import {
  accounts,
  assetClasses,
  assets,
  entryFxSnapshots,
  prices,
  realEstateProperties,
  realEstateValuationSnapshots,
} from "@/db/schema";
import { ensureSchemaOnce } from "@/db/init-schema";
import { D } from "@/domain/decimal";
import { todayIso } from "@/lib/format";
import { recordAuditEvent } from "@/lib/audit";
import { postEntry } from "@/features/ledger/service";
import { nativeUnitPriceUsd } from "@/features/fx/unitPrice";
import { ensureRealizedPnlAccount } from "@/features/accounts/systemAccounts";
import { resolveUsdRateForDate, tomanToUsd } from "@/features/rwa/vehicle/fx";
import { formatMoney } from "@/lib/format";
import { buildRwaSymbol, nextRwaSymbol } from "@/features/rwa/symbol";
import { isOrphanedRwaAsset } from "@/features/rwa/orphanFilter";
import {
  getCity,
  getNeighborhood,
  getPropertyType,
  listCities,
  listNeighborhoods,
  listPropertyTypes,
  normalizeKey,
  seedRealEstateMasterDataIfEmpty,
} from "./masterData";
import {
  allRealEstatePeriodResults,
  cagrPercent,
  latestPoint,
  realEstateHistoryWithDeltas,
} from "./analytics";
import type {
  City,
  CreateRealEstateAssetInput,
  FxRateResolution,
  Neighborhood,
  PropertyType,
  RealEstateAsset,
  RealEstateHistoryRow,
  RealEstateNamePreview,
  RealEstatePeriodResult,
  RealEstatePerformance,
  RealEstatePortfolioSummary,
  RealEstateSnapshotPoint,
  RealEstateValuationSnapshot,
  RecordRealEstateValuationInput,
} from "./types";

/* ─────────────────────── shared helpers ─────────────────────── */

async function ensureRwaAssetClassId(tx: any = db): Promise<string> {
  let [klass] = await tx.select().from(assetClasses).where(eq(assetClasses.code, "RWA")).limit(1);
  if (!klass) {
    [klass] = await tx
      .insert(assetClasses)
      .values({ code: "RWA", name: "دارایی واقعی", color: "#12131c", sortOrder: 90 })
      .onConflictDoNothing()
      .returning();
    if (!klass) [klass] = await tx.select().from(assetClasses).where(eq(assetClasses.code, "RWA")).limit(1);
  }
  if (!klass) throw new Error("کلاس دارایی واقعی ایجاد نشد.");
  return klass.id;
}

/** The ledger's base currency asset (equity leg of opening entries uses it). */
async function ensureUsdAssetId(tx: any = db): Promise<string> {
  let [usdAsset] = await tx.select().from(assets).where(eq(assets.symbol, "USD")).limit(1);
  if (!usdAsset) {
    const classId = await ensureRwaAssetClassId(tx);
    [usdAsset] = await tx
      .insert(assets)
      .values({ symbol: "USD", name: "دلار آمریکا", classId, decimals: 2, priceSource: "manual" })
      .onConflictDoNothing()
      .returning();
    if (!usdAsset) [usdAsset] = await tx.select().from(assets).where(eq(assets.symbol, "USD")).limit(1);
  }
  if (!usdAsset) throw new Error("دارایی پایه (USD) یافت نشد.");
  return usdAsset.id;
}

/**
 * Real Estate ledger accounts (global, consistent with the seeded chart of
 * accounts — 1xxx assets / 3xxx equity):
 *   1600  املاک و مستغلات                 (asset)
 *   3015  سرمایه افتتاحیه تملک‌های تاریخی (equity)
 */
async function ensureRealEstateLedgerAccounts(tx: any = db): Promise<{ assetAccountId: string; openingEquityAccountId: string }> {
  const getByCode = async (code: string) => {
    // Global chart-of-accounts rows (user_id NULL) — consistent with the seed.
    const [row] = await tx.select().from(accounts).where(and(eq(accounts.code, code), isNull(accounts.userId))).limit(1);
    return row ?? null;
  };

  let assetAccount = await getByCode("1600");
  if (!assetAccount) {
    [assetAccount] = await tx
      .insert(accounts)
      .values({ code: "1600", name: "املاک و مستغلات", type: "asset" })
      .onConflictDoNothing({ target: [accounts.userId, accounts.code] })
      .returning();
    if (!assetAccount) assetAccount = await getByCode("1600");
  }

  let equityAccount = await getByCode("3015");
  if (!equityAccount) {
    [equityAccount] = await tx
      .insert(accounts)
      .values({ code: "3015", name: "سرمایه افتتاحیه تملک‌های تاریخی (املاک)", type: "equity" })
      .onConflictDoNothing({ target: [accounts.userId, accounts.code] })
      .returning();
    if (!equityAccount) equityAccount = await getByCode("3015");
  }

  if (!assetAccount || !equityAccount) throw new Error("حساب‌های دفترکل املاک ایجاد نشدند.");
  return { assetAccountId: assetAccount.id, openingEquityAccountId: equityAccount.id };
}

/* ─────────────────────── name & symbol generation ─────────────────────── */

/**
 * Number of already-registered properties with the same
 * (city, neighborhood, property type) — drives the human-readable name suffix.
 * The compact symbol uses the separate global RWA sequence.
 */
async function nextPropertySequence(cityId: string, neighborhoodId: string, propertyTypeId: string): Promise<number> {
  const [row] = await db
    .select({ c: sql<number>`count(*)::int` })
    .from(realEstateProperties)
    .where(
      and(
        eq(realEstateProperties.cityId, cityId),
        eq(realEstateProperties.neighborhoodId, neighborhoodId),
        eq(realEstateProperties.propertyTypeId, propertyTypeId),
      ),
    );
  return (Number(row?.c ?? 0) || 0) + 1;
}

/** Short numeric identifier for properties (`001`, `002`, …). */
export function buildAssetName(p: PropertyType, city: City, hood: Neighborhood, sequence: number, symbol?: string): string {
  return symbol ?? buildRwaSymbol(sequence);
}

/** Compact canonical RWA id (`001`, `002`, …). Shared with vehicles. */
export function buildSymbol(sequence: number): string {
  return buildRwaSymbol(sequence);
}

/** Live preview of the generated name/symbol (used by the registration form). */
export async function previewRealEstateIdentity(
  cityId: string,
  neighborhoodId: string,
  propertyTypeId: string,
): Promise<RealEstateNamePreview | null> {
  const [city, hood, ptype] = await Promise.all([getCity(cityId), getNeighborhood(neighborhoodId), getPropertyType(propertyTypeId)]);
  if (!city || !hood || !ptype) return null;
  const sequence = await nextPropertySequence(cityId, neighborhoodId, propertyTypeId);
  const symbol = await nextRwaSymbol();
  return {
    assetName: symbol,
    // Preview is advisory; the final transaction resolves and locks again.
    symbol,
    sequence,
  };
}

/* ─────────────────────── performance (derived, never stored) ─────────────────────── */

export function computePerformance(
  purchaseToman: string | null,
  currentToman: string | null,
  purchaseUsd: string | null,
  currentUsd: string | null,
): RealEstatePerformance {
  if (!purchaseToman || !currentToman) {
    return { gainToman: null, roiToman: null, gainUsd: null, roiUsd: null };
  }
  const pT = D(purchaseToman);
  const cT = D(currentToman);
  const gainToman = cT.sub(pT);
  const roiToman = pT.gt(0) ? gainToman.div(pT).mul("100").toFixed(2) : null;
  let gainUsd: string | null = null;
  let roiUsd: string | null = null;
  if (purchaseUsd && currentUsd && D(purchaseUsd).gt(0)) {
    const pU = D(purchaseUsd);
    const cU = D(currentUsd);
    gainUsd = cU.sub(pU).toFixed(2);
    roiUsd = pU.gt(0) ? cU.sub(pU).div(pU).mul("100").toFixed(2) : null;
  }
  return { gainToman: gainToman.toFixed(0), roiToman, gainUsd, roiUsd };
}

/* ─────────────────────── valuation snapshots (immutable history) ─────────────────────── */

const num = (v: unknown): string | null => (v === null || v === undefined ? null : D(v as string).toString());
const tomanStr = (v: unknown): string | null => (v === null || v === undefined ? null : D(v as string).toFixed(0));
const usdStr = (v: unknown): string | null => (v === null || v === undefined ? null : D(v as string).toFixed(2));

function mapSnapshot(row: typeof realEstateValuationSnapshots.$inferSelect): RealEstateValuationSnapshot {
  return {
    id: row.id,
    propertyId: row.propertyId,
    assetId: row.assetId,
    userId: row.userId ?? null,
    snapshotDate: row.snapshotDate,
    snapshotDatePersian: row.snapshotDatePersian ?? null,
    currentValueToman: tomanStr(row.currentValueToman) ?? "0",
    usdRate: num(row.usdRate) ?? "0",
    usdRateSource: row.usdRateSource ?? null,
    usdRateDate: row.usdRateDate ?? null,
    currentValueUsd: usdStr(row.currentValueUsd) ?? "0",
    source: row.source,
    note: row.note ?? null,
    createdAt: row.createdAt?.toISOString() ?? new Date().toISOString(),
  };
}

/**
 * INSERT a new immutable valuation snapshot inside a transaction. Existing
 * snapshots are never updated: a second valuation for the same day is
 * refused — a new value must be recorded on a new date (same rule as the
 * vehicle module). This is what makes "ارزش سه ماه پیش" undeletable.
 */
async function insertValuationSnapshot(
  tx: any,
  input: {
    propertyId: string;
    assetId: string;
    userId?: string | null;
    snapshotDate: string;
    snapshotDatePersian?: string | null;
    currentValueToman: string;
    usdRate: string;
    usdRateSource?: string | null;
    usdRateDate?: string | null;
    currentValueUsd: string;
    source?: string;
    note?: string | null;
  },
): Promise<string> {
  const [existing] = await tx
    .select({ id: realEstateValuationSnapshots.id })
    .from(realEstateValuationSnapshots)
    .where(
      and(
        eq(realEstateValuationSnapshots.propertyId, input.propertyId),
        eq(realEstateValuationSnapshots.snapshotDate, input.snapshotDate),
      ),
    )
    .limit(1);
  if (existing) {
    throw new Error(
      "برای این تاریخ ارزش‌گذاری ثبت شده است. اسنپ‌شات‌های قبلی تغییرناپذیرند؛ برای ارزش جدید یک تاریخ جدید ثبت کنید.",
    );
  }
  const [row] = await tx
    .insert(realEstateValuationSnapshots)
    .values({
      propertyId: input.propertyId,
      assetId: input.assetId,
      userId: input.userId ?? null,
      snapshotDate: input.snapshotDate,
      snapshotDatePersian: input.snapshotDatePersian ?? null,
      currentValueToman: D(input.currentValueToman).toFixed(0),
      usdRate: D(input.usdRate).toString(),
      usdRateSource: input.usdRateSource ?? "manual",
      usdRateDate: input.usdRateDate ?? input.snapshotDate,
      currentValueUsd: input.currentValueUsd,
      source: input.source ?? "manual",
      note: input.note ?? null,
    })
    .returning({ id: realEstateValuationSnapshots.id });
  return row.id;
}

/** All valuation snapshots of one property, oldest first (immutable history). */
export async function listRealEstateValuationSnapshots(
  propertyId: string,
  userId?: string | null,
): Promise<RealEstateValuationSnapshot[]> {
  const rows = await db
    .select()
    .from(realEstateValuationSnapshots)
    .where(
      and(
        eq(realEstateValuationSnapshots.propertyId, propertyId),
        userId ? eq(realEstateValuationSnapshots.userId, userId) : undefined,
      ),
    )
    .orderBy(asc(realEstateValuationSnapshots.snapshotDate));
  return rows.map(mapSnapshot);
}

/**
 * Snapshots of a tenant's whole portfolio, grouped by property. Scoped at the
 * DB query level (NULL-owned rows are NOT shared with identified tenants).
 */
async function loadSnapshotsByProperty(userId?: string | null): Promise<Map<string, RealEstateValuationSnapshot[]>> {
  const rows = await db
    .select()
    .from(realEstateValuationSnapshots)
    .where(userId ? eq(realEstateValuationSnapshots.userId, userId) : undefined)
    .orderBy(asc(realEstateValuationSnapshots.snapshotDate));
  const map = new Map<string, RealEstateValuationSnapshot[]>();
  for (const row of rows) {
    const list = map.get(row.propertyId) ?? [];
    list.push(mapSnapshot(row));
    map.set(row.propertyId, list);
  }
  return map;
}

/* ─────────────────────── mapping ─────────────────────── */

type PropertyRow = typeof realEstateProperties.$inferSelect & {
  assetSymbol: string;
  assetName: string;
};

function mapAsset(r: PropertyRow): RealEstateAsset {
  return {
    id: r.id,
    assetId: r.assetId,
    symbol: r.assetSymbol,
    assetName: r.assetName,
    userId: r.userId,
    cityId: r.cityId ?? null,
    cityNameFa: null,
    cityNameEn: null,
    cityCode: null,
    neighborhoodId: r.neighborhoodId ?? null,
    neighborhoodNameFa: null,
    neighborhoodNameEn: null,
    neighborhoodCode: null,
    propertyTypeId: r.propertyTypeId ?? null,
    propertyTypeNameFa: null,
    propertyTypeNameEn: null,
    propertyTypeCode: null,
    propertyType: r.propertyType ?? null,
    area: r.area ?? null,
    address: r.address ?? null,
    sizeSqm: r.sizeSqm === null || r.sizeSqm === undefined ? null : D(r.sizeSqm).toFixed(2),
    floor: r.floor ?? null,
    yearBuilt: r.yearBuilt ?? null,
    deedNumber: r.deedNumber ?? null,
    notes: r.notes ?? null,
    acquisitionDate: r.acquisitionDate ?? null,
    acquisitionDatePersian: r.acquisitionDatePersian ?? null,
    valuationDate: r.valuationDate ?? null,
    valuationDatePersian: r.valuationDatePersian ?? null,
    systemEntryDate: r.systemEntryDate ?? null,
    isHistorical: r.isHistorical,
    purchasePriceToman: tomanStr(r.purchasePriceToman),
    purchaseFxRate: num(r.purchaseFxRate),
    purchaseFxRateSource: r.purchaseFxRateSource ?? null,
    purchaseFxRateDate: r.purchaseFxRateDate ?? null,
    purchaseValueUsd: usdStr(r.purchaseValueUsd),
    currentValueToman: tomanStr(r.currentValueToman),
    valuationFxRate: num(r.valuationFxRate),
    valuationFxRateSource: r.valuationFxRateSource ?? null,
    valuationFxRateDate: r.valuationFxRateDate ?? null,
    currentValueUsd: usdStr(r.currentValueUsd),
    ledgerEntryId: r.ledgerEntryId ?? null,
    createdAt: r.createdAt?.toISOString() ?? new Date().toISOString(),
    updatedAt: r.updatedAt?.toISOString() ?? null,
  };
}

/* ─────────────────────── ledger posting ─────────────────────── */

/**
 * The double-entry record of the acquisition, dated at the REAL ownership
 * date. Because the acquisition may predate the system, the credit side is
 * Opening Equity (opening balance / prior-period acquisition) — never a cash
 * outflow at the system-entry date.
 */
async function postRealEstateOpeningEntry(
  tx: any,
  input: {
    userId?: string | null;
    assetId: string;
    symbol: string;
    assetName: string;
    entryDate: string;
    acquisitionDatePersian: string | null;
    purchaseValueUsd: string;
    purchasePriceToman: string; // قیمت خرید واقعی کاربر (تومان)
    /** USD rate of the acquisition date, frozen (IRT per 1 USD). */
    purchaseFxRate: string;
    /** Source of the frozen rate: exact | nearest | manual | current | fallback. */
    purchaseFxRateSource: string;
    /** Effective date of the frozen rate (may differ from entryDate when nearest). */
    purchaseFxRateDate: string;
  },
): Promise<string> {
  const { assetAccountId, openingEquityAccountId } = await ensureRealEstateLedgerAccounts(tx);
  const usdAssetId = await ensureUsdAssetId(tx);

  const result = await postEntry(
    {
      entryDate: input.entryDate,
      type: "opening",
      description: `تملک تاریخی — ملک ${input.symbol}${input.acquisitionDatePersian ? ` — ${input.acquisitionDatePersian}` : ""} | قیمت خرید: ${formatMoney(input.purchasePriceToman, "IRT")}`,
      source: "manual",
      reference: input.symbol,
      userId: input.userId ?? undefined,
      idempotencyKey: `real-estate-acquisition:${input.assetId}`,
      postings: [
        {
          accountId: assetAccountId,
          assetId: input.assetId,
          quantity: "1",
          baseValue: input.purchaseValueUsd,
          memo: `تملک ملک — قیمت خرید: ${formatMoney(input.purchasePriceToman, "IRT")}`,
        },
        {
          accountId: openingEquityAccountId,
          assetId: usdAssetId,
          quantity: D(input.purchaseValueUsd).neg().toString(),
          baseValue: D(input.purchaseValueUsd).neg().toString(),
          memo: "افتتاحیه تملک تاریخی (Opening Balance)",
        },
      ],
    },
    tx,
  );

  // Freeze the contractual Toman at commit (Presentation Layer, display & audit
  // only — never part of the double-entry). This is what the Human Finance
  // Layer uses so a historical acquisition shows its real purchase price in
  // Toman, never a current USD→IRT re-derivation. Written atomically with the
  // ledger entry; idempotent by the unique entry_id.
  await tx
    .insert(entryFxSnapshots)
    .values({
      entryId: result.id,
      irtAmount: D(input.purchasePriceToman).toFixed(0),
      usdAmount: D(input.purchaseValueUsd).toString(),
      fxRate: D(input.purchaseFxRate).toString(),
      rateSource: input.purchaseFxRateSource,
      rateDate: input.purchaseFxRateDate,
    })
    .onConflictDoNothing();

  return result.id;
}

/** Record the current (USD) value into the prices table so holdings /
 *  net-worth / portfolio read it automatically (qty 1 × latest price). */
async function recordCurrentPrice(
  tx: any,
  assetId: string,
  currentValueUsd: string,
  valuationDate: string,
): Promise<void> {
  if (D(currentValueUsd).lte(0)) return;
  await tx
    .insert(prices)
    .values({ assetId, asOf: valuationDate, priceBase: D(currentValueUsd).toString(), source: "real_estate_valuation" })
    .onConflictDoUpdate({
      target: [prices.assetId, prices.asOf],
      set: { priceBase: D(currentValueUsd).toString(), source: "real_estate_valuation" },
    });
}

/* ─────────────────────── create ─────────────────────── */

/**
 * ثبت ملک — تمام قواعد ماژول در یک تراکنش:
 *  1. شهر/محله/نوع ملک فقط از Master Data فعال
 *  2. نام و شناسه کوتاه خودکار (کاربر هیچ‌کدام را وارد نمی‌کند)
 *  3. تاریخ شمسی → میلادی (ISO) به‌عنوان مقدار استاندارد
 *  4. قیمت خرید: نرخ دلارِ تاریخ تملک؛ ارزش فعلی: نرخ دلارِ تاریخ ارزش‌گذاری
 *  5. سند افتتاحیه دفترکل با تاریخِ تملکِ واقعی (نه تاریخ ثبت در سیستم)
 *  6. ارزش فعلی واردِ Aggregate می‌شود (جدول prices → سبد و ارزش خالص)
 */
export async function createRealEstateAsset(input: CreateRealEstateAssetInput): Promise<{
  id: string;
  assetId: string;
  symbol: string;
  assetName: string;
  ledgerEntryId: string;
}> {
  if (!input.cityId || !input.neighborhoodId || !input.propertyTypeId) {
    throw new Error("شهر، منطقه/محله و نوع ملک باید از فهرست انتخاب شوند.");
  }
  const [city, hood, ptype] = await Promise.all([
    getCity(input.cityId),
    getNeighborhood(input.neighborhoodId),
    getPropertyType(input.propertyTypeId),
  ]);
  if (!city || !city.isActive) throw new Error("شهر انتخاب‌شده معتبر نیست.");
  if (!hood || hood.cityId !== city.id) throw new Error("محله انتخاب‌شده متعلق به این شهر نیست.");
  if (!hood.isActive) throw new Error("محله انتخاب‌شده غیرفعال است.");
  if (!ptype || !ptype.isActive) throw new Error("نوع ملک انتخاب‌شده معتبر نیست.");

  const acquisitionDate = (input.acquisitionDate || "").slice(0, 10);
  if (!acquisitionDate) throw new Error("تاریخ تملک (شمسی) الزامی است و باید معتبر باشد.");
  const valuationDate = (input.valuationDate || "").slice(0, 10);
  if (!valuationDate) throw new Error("تاریخ ارزش‌گذاری (شمسی) الزامی است و باید معتبر باشد.");

  const purchase = D(input.purchasePriceToman ?? "0");
  if (purchase.lte(0)) throw new Error("قیمت خرید (تومان) الزامی است و باید بزرگ‌تر از صفر باشد.");
  const current = D(input.currentValueToman ?? "0");
  if (current.lte(0)) throw new Error("ارزش فعلی (تومان) الزامی است و باید بزرگ‌تر از صفر باشد.");

  // Historical FX — the rate of the ACQUISITION date, frozen forever.
  let purchaseFx: FxRateResolution;
  if (input.purchaseFxRate && D(input.purchaseFxRate).gt(0)) {
    purchaseFx = { rate: D(input.purchaseFxRate).toString(), effectiveDate: acquisitionDate, source: "manual", isExact: true };
  } else {
    purchaseFx = await resolveUsdRateForDate(acquisitionDate, input.userId ?? null);
  }
  if (D(purchaseFx.rate).lte(0)) throw new Error("نرخ دلار تاریخ تملک در دسترس نیست.");
  const purchaseValueUsd = tomanToUsd(purchase.toFixed(0), purchaseFx.rate);

  // Historical FX — the rate of the VALUATION date, frozen forever.
  let valuationFx: FxRateResolution;
  if (input.valuationFxRate && D(input.valuationFxRate).gt(0)) {
    valuationFx = { rate: D(input.valuationFxRate).toString(), effectiveDate: valuationDate, source: "manual", isExact: true };
  } else {
    valuationFx = await resolveUsdRateForDate(valuationDate, input.userId ?? null);
  }
  if (D(valuationFx.rate).lte(0)) throw new Error("نرخ دلار تاریخ ارزش‌گذاری در دسترس نیست.");
  const currentValueUsd = tomanToUsd(current.toFixed(0), valuationFx.rate);

  const sequence = await nextPropertySequence(city.id, hood.id, ptype.id);
  const systemEntryDate = todayIso();
  const isHistorical = acquisitionDate < systemEntryDate;

  const classId = await ensureRwaAssetClassId();

  const created = await db.transaction(async (tx) => {
    const symbol = await nextRwaSymbol(tx, classId);
    const assetName = symbol;
    const [asset] = await tx
      .insert(assets)
      .values({ name: assetName, symbol, classId, decimals: 2, priceSource: "manual" })
      .returning();
    if (!asset) throw new Error("ایجاد رکورد دارایی ناموفق بود.");

    const [prop] = await tx
      .insert(realEstateProperties)
      .values({
        assetId: asset.id,
        userId: input.userId ?? null,
        // master-data identity
        cityId: city.id,
        neighborhoodId: hood.id,
        propertyTypeId: ptype.id,
        // legacy denormalised copies (kept in sync for old consumers)
        city: city.nameEn,
        area: hood.nameEn,
        propertyType: ptype.code.toLowerCase(),
        address: input.address?.trim() || null,
        sizeSqm: input.sizeSqm ? D(input.sizeSqm).toString() : null,
        floor: input.floor ?? null,
        yearBuilt: input.yearBuilt ?? null,
        deedNumber: input.deedNumber?.trim() || null,
        notes: input.notes?.trim() || null,
        // timing
        acquisitionDate,
        acquisitionDatePersian: input.acquisitionDatePersian || null,
        valuationDate,
        valuationDatePersian: input.valuationDatePersian || null,
        systemEntryDate,
        isHistorical,
        // purchase
        purchasePriceToman: purchase.toFixed(0),
        purchaseFxRate: D(purchaseFx.rate).toString(),
        purchaseFxRateSource: purchaseFx.source,
        purchaseFxRateDate: purchaseFx.effectiveDate,
        purchaseValueUsd,
        // current valuation
        currentValueToman: current.toFixed(0),
        valuationFxRate: D(valuationFx.rate).toString(),
        valuationFxRateSource: valuationFx.source,
        valuationFxRateDate: valuationFx.effectiveDate,
        currentValueUsd,
      })
      .returning();

    // Freeze the initial valuation as an IMMUTABLE snapshot — the first point
    // of the property's valuation history (append-only, same rule as vehicles).
    await insertValuationSnapshot(tx, {
      propertyId: prop.id,
      assetId: asset.id,
      userId: input.userId ?? null,
      snapshotDate: valuationDate,
      snapshotDatePersian: input.valuationDatePersian || null,
      currentValueToman: current.toFixed(0),
      usdRate: D(valuationFx.rate).toString(),
      usdRateSource: valuationFx.source,
      usdRateDate: valuationFx.effectiveDate,
      currentValueUsd,
      note: "ارزش‌گذاری اولیه (هنگام ثبت ملک)",
    });

    const ledgerEntryId = await postRealEstateOpeningEntry(tx, {
      userId: input.userId ?? null,
      assetId: asset.id,
      symbol,
      assetName,
      entryDate: acquisitionDate,
      acquisitionDatePersian: input.acquisitionDatePersian || null,
      purchaseValueUsd,
      purchasePriceToman: purchase.toFixed(0),
      purchaseFxRate: D(purchaseFx.rate).toString(),
      purchaseFxRateSource: purchaseFx.source,
      purchaseFxRateDate: purchaseFx.effectiveDate,
    });

    await tx
      .update(realEstateProperties)
      .set({ ledgerEntryId, updatedAt: new Date() })
      .where(eq(realEstateProperties.id, prop.id));

    await recordCurrentPrice(tx, asset.id, currentValueUsd, valuationDate);

    await recordAuditEvent(
      {
        action: "CREATE_REAL_ESTATE_ASSET",
        entityType: "real_estate_property",
        entityId: prop.id,
        userId: input.userId ?? null,
        result: "SUCCESS",
        payload: {
          symbol,
          assetName,
          acquisitionDate,
          valuationDate,
          purchaseValueUsd,
          currentValueUsd,
          ledgerEntryId,
          isHistorical,
        },
      },
      tx,
    );

    return { id: prop.id, assetId: asset.id, ledgerEntryId, symbol };
  });

  return { ...created, assetName: created.symbol };
}

/* ─────────────────────── reads / dashboard ─────────────────────── */

// SECURITY (multi-user isolation): scoping MUST happen at the DB query level
// (WHERE user_id = :currentUserId), never via post-filtering in application code.
// When a `userId` is provided, only rows owned by that tenant are returned;
// NULL-owned private rows are NOT shared/system data and stay excluded.
async function loadProperties(userId?: string | null): Promise<RealEstateAsset[]> {
  const rows = await db
    .select({
      p: realEstateProperties,
      assetSymbol: assets.symbol,
      assetName: assets.name,
    })
    .from(realEstateProperties)
    .innerJoin(assets, eq(assets.id, realEstateProperties.assetId))
    .where(
      userId
        ? and(eq(realEstateProperties.userId, userId), isNull(assets.deletedAt))
        : isNull(assets.deletedAt),
    )
    .orderBy(desc(realEstateProperties.createdAt));

  const filtered = rows;

  const cities = await listCities(true);
  const hoods = await listNeighborhoods(undefined, true);
  const types = await listPropertyTypes(true);
  const cityById = new Map(cities.map((c) => [c.id, c]));
  const hoodById = new Map(hoods.map((h) => [h.id, h]));
  const typeById = new Map(types.map((t) => [t.id, t]));

  return filtered.map(({ p, assetSymbol, assetName }) => {
    const asset = mapAsset({ ...p, assetSymbol, assetName });
    const c = asset.cityId ? cityById.get(asset.cityId) : null;
    const h = asset.neighborhoodId ? hoodById.get(asset.neighborhoodId) : null;
    const t = asset.propertyTypeId ? typeById.get(asset.propertyTypeId) : null;
    return {
      ...asset,
      cityNameFa: c?.nameFa ?? asset.cityNameFa,
      cityNameEn: c?.nameEn ?? asset.cityNameEn,
      cityCode: c?.code ?? asset.cityCode,
      neighborhoodNameFa: h?.nameFa ?? asset.neighborhoodNameFa,
      neighborhoodNameEn: h?.nameEn ?? asset.neighborhoodNameEn,
      neighborhoodCode: h?.code ?? asset.neighborhoodCode,
      propertyTypeNameFa: t?.nameFa ?? asset.propertyTypeNameFa,
      propertyTypeNameEn: t?.nameEn ?? asset.propertyTypeNameEn,
      propertyTypeCode: t?.code ?? asset.propertyTypeCode,
    };
  });
}

export async function listRealEstateAssets(userId?: string | null): Promise<RealEstateAsset[]> {
  return loadProperties(userId);
}

export async function getRealEstateAsset(propertyId: string): Promise<RealEstateAsset | null> {
  const [row] = await db
    .select({ p: realEstateProperties, assetSymbol: assets.symbol, assetName: assets.name })
    .from(realEstateProperties)
    .innerJoin(assets, eq(assets.id, realEstateProperties.assetId))
    .where(eq(realEstateProperties.id, propertyId))
    .limit(1);
  if (!row) return null;
  const asset = mapAsset({ ...row.p, assetSymbol: row.assetSymbol, assetName: row.assetName });
  const [city, hood, ptype] = await Promise.all([
    asset.cityId ? getCity(asset.cityId) : null,
    asset.neighborhoodId ? getNeighborhood(asset.neighborhoodId) : null,
    asset.propertyTypeId ? getPropertyType(asset.propertyTypeId) : null,
  ]);
  return {
    ...asset,
    cityNameFa: city?.nameFa ?? asset.cityNameFa,
    cityNameEn: city?.nameEn ?? asset.cityNameEn,
    cityCode: city?.code ?? asset.cityCode,
    neighborhoodNameFa: hood?.nameFa ?? asset.neighborhoodNameFa,
    neighborhoodNameEn: hood?.nameEn ?? asset.neighborhoodNameEn,
    neighborhoodCode: hood?.code ?? asset.neighborhoodCode,
    propertyTypeNameFa: ptype?.nameFa ?? asset.propertyTypeNameFa,
    propertyTypeNameEn: ptype?.nameEn ?? asset.propertyTypeNameEn,
    propertyTypeCode: ptype?.code ?? asset.propertyTypeCode,
  };
}

export type RealEstateDashboardItem = RealEstateAsset & {
  performance: RealEstatePerformance;
  /** نقطه خرید — مبنای تغییرناپذیر مقایسه‌های «از تاریخ تملک» */
  purchasePoint: RealEstateSnapshotPoint | null;
  /** تاریخچه کامل ارزش‌گذاری‌ها (اسنپ‌شات‌های تغییرناپذیر)، قدیمی‌ترین اول */
  snapshots: RealEstateValuationSnapshot[];
  /** ردیف‌های تاریخچه با تغییر نسبت به ارزش‌گذاری قبلی */
  history: RealEstateHistoryRow[];
  /** رشد/افت تومانی و دلاری در بازه‌های ۱م/۳م/۶م/۱س/… و از تملک و کل دوره */
  periods: RealEstatePeriodResult[];
  cagrToman: string | null;
  cagrUsd: string | null;
};

/** Immutable purchase point — the frozen basis of «از تاریخ تملک» analyses. */
export function realEstatePurchasePointOf(a: RealEstateAsset): RealEstateSnapshotPoint | null {
  if (!a.acquisitionDate || !a.purchasePriceToman || !a.purchaseFxRate) return null;
  return {
    date: a.acquisitionDate,
    valueToman: a.purchasePriceToman,
    usdRate: a.purchaseFxRate,
    valueUsd: a.purchaseValueUsd ?? tomanToUsd(a.purchasePriceToman, a.purchaseFxRate),
  };
}

export async function getRealEstateDashboard(userId?: string | null): Promise<RealEstateDashboardItem[]> {
  const assetsList = await loadProperties(userId);
  const snapshotsByProperty = await loadSnapshotsByProperty(userId);
  const today = todayIso();

  return assetsList.map((a) => {
    const snapshots = snapshotsByProperty.get(a.id) ?? [];
    const points = snapshots.map((s) => ({
      date: s.snapshotDate,
      valueToman: s.currentValueToman,
      usdRate: s.usdRate,
      valueUsd: s.currentValueUsd,
    }));
    const purchasePoint = realEstatePurchasePointOf(a);
    const latest = latestPoint(points);

    let cagrToman: string | null = null;
    let cagrUsd: string | null = null;
    if (purchasePoint && latest) {
      cagrToman = cagrPercent(purchasePoint.valueToman, latest.valueToman, purchasePoint.date, latest.date);
      cagrUsd = cagrPercent(purchasePoint.valueUsd, latest.valueUsd, purchasePoint.date, latest.date);
    }

    return {
      ...a,
      performance: computePerformance(a.purchasePriceToman, a.currentValueToman, a.purchaseValueUsd, a.currentValueUsd),
      purchasePoint,
      snapshots,
      history: realEstateHistoryWithDeltas(points),
      periods: allRealEstatePeriodResults(points, { todayIso: today, purchasePoint }),
      cagrToman,
      cagrUsd,
    };
  });
}

export async function getRealEstatePortfolioSummary(userId?: string | null): Promise<RealEstatePortfolioSummary> {
  const dashboard = await getRealEstateDashboard(userId);

  let totalCurrentToman = D("0");
  let totalCurrentUsd = D("0");
  let totalPurchaseToman = D("0");
  let totalPurchaseUsd = D("0");
  let unvaluedCount = 0;

  for (const a of dashboard) {
    if (!a.currentValueToman) unvaluedCount++;
    if (a.currentValueToman) totalCurrentToman = totalCurrentToman.add(a.currentValueToman);
    if (a.currentValueUsd) totalCurrentUsd = totalCurrentUsd.add(a.currentValueUsd);
    if (a.purchasePriceToman) totalPurchaseToman = totalPurchaseToman.add(a.purchasePriceToman);
    if (a.purchaseValueUsd) totalPurchaseUsd = totalPurchaseUsd.add(a.purchaseValueUsd);
  }

  const totalGainToman = totalCurrentToman.sub(totalPurchaseToman);
  const totalGainUsd = totalCurrentUsd.sub(totalPurchaseUsd);

  return {
    count: dashboard.length,
    unvaluedCount,
    totalCurrentToman: totalCurrentToman.toFixed(0),
    totalCurrentUsd: totalCurrentUsd.toFixed(2),
    totalPurchaseToman: totalPurchaseToman.toFixed(0),
    totalPurchaseUsd: totalPurchaseUsd.toFixed(2),
    totalGainToman: totalGainToman.toFixed(0),
    totalGainUsd: totalGainUsd.toFixed(2),
    roiToman: totalPurchaseToman.gt(0) ? totalGainToman.div(totalPurchaseToman).mul("100").toFixed(2) : null,
    roiUsd: totalPurchaseUsd.gt(0) ? totalGainUsd.div(totalPurchaseUsd).mul("100").toFixed(2) : null,
  };
}

/* ─────────────────────── revaluation (append-only) ─────────────────────── */

/**
 * ارزش‌گذاری جدید — Current Value changes ONLY here.
 *  - A new IMMUTABLE valuation snapshot is appended first (same-date refused);
 *    previous valuations are never updated or deleted → the Toman value AND
 *    the frozen USD rate of «یک ماه پیش / سه ماه پیش / شش ماه پیش» survive.
 *  - The ledger entry and the purchase history are NEVER touched (immutable).
 *  - A new price row (prices) makes the aggregate / net-worth use the new value.
 */
export async function recordRealEstateValuation(input: RecordRealEstateValuationInput): Promise<{
  id: string;
  currentValueToman: string;
  currentValueUsd: string;
  valuationFxRate: string;
}> {
  // SECURITY (H-01): tenancy boundary enforced at the DATABASE query level.
  // When a user identity is present (multi-user mode), the property is only
  // loadable if it belongs to that exact user — a cross-user propertyId
  // simply does not exist for this caller (404 semantics, nothing leaks and
  // nothing can be mutated). In legacy single-tenant mode there is no
  // identity to scope by, so the global lookup is kept.
  const [prop] = await db
    .select()
    .from(realEstateProperties)
    .where(
      input.userId
        ? and(eq(realEstateProperties.id, input.propertyId), eq(realEstateProperties.userId, input.userId))
        : eq(realEstateProperties.id, input.propertyId),
    )
    .limit(1);
  if (!prop) throw new Error("ملک یافت نشد یا متعلق به شما نیست.");

  const valuationDate = (input.valuationDate || "").slice(0, 10);
  if (!valuationDate) throw new Error("تاریخ ارزش‌گذاری (شمسی) الزامی است.");
  const current = D(input.currentValueToman ?? "0");
  if (current.lte(0)) throw new Error("ارزش فعلی باید بزرگ‌تر از صفر باشد.");

  let valuationFx: FxRateResolution;
  if (input.valuationFxRate && D(input.valuationFxRate).gt(0)) {
    valuationFx = { rate: D(input.valuationFxRate).toString(), effectiveDate: valuationDate, source: "manual", isExact: true };
  } else {
    valuationFx = await resolveUsdRateForDate(valuationDate, input.userId ?? null);
  }
  if (D(valuationFx.rate).lte(0)) throw new Error("نرخ دلار تاریخ ارزش‌گذاری در دسترس نیست.");
  const currentValueUsd = tomanToUsd(current.toFixed(0), valuationFx.rate);

  const updated = await db.transaction(async (tx) => {
    // 1. Append the IMMUTABLE valuation snapshot FIRST — history is never
    //    deleted or rewritten; a same-date valuation is refused.
    const snapshotId = await insertValuationSnapshot(tx, {
      propertyId: prop.id,
      assetId: prop.assetId,
      userId: input.userId ?? null,
      snapshotDate: valuationDate,
      snapshotDatePersian: input.valuationDatePersian ?? null,
      currentValueToman: current.toFixed(0),
      usdRate: D(valuationFx.rate).toString(),
      usdRateSource: valuationFx.source,
      usdRateDate: valuationFx.effectiveDate,
      currentValueUsd,
      note: input.note ?? null,
    });

    // 2. Only the CURRENT valuation pointer on the property row moves forward.
    const [row] = await tx
      .update(realEstateProperties)
      .set({
        currentValueToman: current.toFixed(0),
        valuationFxRate: D(valuationFx.rate).toString(),
        valuationFxRateSource: valuationFx.source,
        valuationFxRateDate: valuationFx.effectiveDate,
        currentValueUsd,
        valuationDate,
        valuationDatePersian: input.valuationDatePersian ?? null,
        updatedAt: new Date(),
      })
      .where(eq(realEstateProperties.id, prop.id))
      .returning();

    await recordCurrentPrice(tx, prop.assetId, currentValueUsd, valuationDate);

    await recordAuditEvent(
      {
        action: "REVALUE_REAL_ESTATE_ASSET",
        entityType: "real_estate_property",
        entityId: prop.id,
        userId: input.userId ?? null,
        result: "SUCCESS",
        payload: {
          valuationDate,
          currentValueToman: current.toFixed(0),
          currentValueUsd,
          valuationFxRate: D(valuationFx.rate).toString(),
          source: valuationFx.source,
          ledgerEntryId: prop.ledgerEntryId,
          valuationSnapshotId: snapshotId,
        },
      },
      tx,
    );

    return row;
  });

  if (!updated) throw new Error("به‌روزرسانی ارزش‌گذاری ناموفق بود.");
  return {
    id: updated.id,
    currentValueToman: D(updated.currentValueToman ?? "0").toFixed(0),
    currentValueUsd: D(updated.currentValueUsd ?? "0").toFixed(2),
    valuationFxRate: D(updated.valuationFxRate ?? "0").toString(),
  };
}

/* ─────────────────────── sale (realized gain → ledger) ─────────────────────── */

/**
 * The receiving account of a sale must be an ASSET account in a money unit,
 * owned by this tenant (or a shared global row). Returns null when the id does
 * not qualify — the caller then refuses the write instead of inventing a cash
 * destination (audit F-03: no foreign account, ever).
 */
async function resolveSalePayoutAccount(
  accountId: string,
  userId?: string | null,
): Promise<{ id: string; assetId: string } | null> {
  const scope = userId ? or(eq(accounts.userId, userId), isNull(accounts.userId)) : sql`1=1`;
  const [row] = await db
    .select({ id: accounts.id, assetId: accounts.assetId, type: accounts.type })
    .from(accounts)
    .where(and(eq(accounts.id, accountId), scope, sql`${accounts.deletedAt} is null`))
    .limit(1);
  if (!row || row.type !== "asset" || !row.assetId) return null;
  return { id: row.id, assetId: row.assetId };
}

/**
 * فروش ملک — the property leaves the portfolio through the SAME unified write
 * path as every other transaction (`postEntry`), in ONE atomic transaction:
 *
 *   1. The carrying value is removed from the real-estate asset account (1600)
 *      with quantity −1 (the opening entry posted +1 — the position is a single
 *      unit, never a FIFO lot). No lot is created or consumed.
 *   2. The sale proceeds are credited to the chosen cash account.
 *   3. The difference (sale value − carrying value) is booked to the realized
 *      P&L account (4100) — the real-asset gain/loss therefore flows into the
 *      unified realized P&L read model (`getRealizedPnl`), WITHOUT ever being
 *      forced through the FIFO engine.
 *   4. The property row + valuation snapshots are removed and the asset is
 *      soft-deleted (the same cleanup as `deleteRealEstateAsset`), so the sold
 *      property stops contributing to holdings / portfolio / net worth — its
 *      unrealized P&L becomes exactly 0 while the realized result stays in the
 *      immutable ledger.
 *
 * The frozen Toman sale price and the sale-date FX rate are written to
 * `entry_fx_snapshots` atomically with the ledger entry.
 */
export async function sellRealEstateAsset(input: {
  propertyId: string;
  saleDate: string;
  saleDatePersian?: string | null;
  salePriceToman: string;
  saleFxRate?: string | null;
  saleAccountId: string;
  note?: string | null;
  userId?: string | null;
}): Promise<{
  assetId: string;
  symbol: string;
  ledgerEntryId: string;
  saleValueUsd: string;
  realizedToman: string;
  realizedUsd: string;
}> {
  // 1. Load the property + asset (tenant-scoped at the DB query level).
  const [prop] = await db
    .select({
      p: realEstateProperties,
      assetSymbol: assets.symbol,
    })
    .from(realEstateProperties)
    .innerJoin(assets, eq(assets.id, realEstateProperties.assetId))
    .where(
      input.userId
        ? and(eq(realEstateProperties.id, input.propertyId), eq(realEstateProperties.userId, input.userId))
        : eq(realEstateProperties.id, input.propertyId),
    )
    .limit(1);
  if (!prop) throw new Error("ملک یافت نشد یا متعلق به شما نیست.");

  const saleDate = (input.saleDate || "").slice(0, 10);
  if (!saleDate) throw new Error("تاریخ فروش الزامی است.");
  const salePrice = D(String(input.salePriceToman ?? "").replace(/[,٬\s]/g, ""));
  if (salePrice.lte(0)) throw new Error("قیمت فروش (تومان) الزامی است و باید بزرگ‌تر از صفر باشد.");

  const carrying = D(prop.p.purchaseValueUsd ?? "0");
  if (carrying.lte(0)) {
    throw new Error("این ملک سند افتتاحیه حسابداری ندارد و فروش از مسیر دفترکل ممکن نیست.");
  }
  const purchaseToman = D(prop.p.purchasePriceToman ?? "0");

  // 2. FX of the sale date, frozen (manual override or historical lookup).
  let saleFx: FxRateResolution;
  if (input.saleFxRate && D(input.saleFxRate).gt(0)) {
    saleFx = { rate: D(input.saleFxRate).toString(), effectiveDate: saleDate, source: "manual", isExact: true };
  } else {
    saleFx = await resolveUsdRateForDate(saleDate, input.userId ?? null);
  }
  if (D(saleFx.rate).lte(0)) throw new Error("نرخ دلار تاریخ فروش در دسترس نیست.");
  const saleValueUsd = tomanToUsd(salePrice.toFixed(0), saleFx.rate);

  // 3. Resolve the cash account (asset type, tenant-owned or global).
  const cashAccount = await resolveSalePayoutAccount(input.saleAccountId, input.userId);
  if (!cashAccount) throw new Error("حساب دریافت وجه فروش نامعتبر یا متعلق به این کاربر نیست.");

  const realizedUsd = D(saleValueUsd).sub(carrying);
  const realizedToman = salePrice.sub(purchaseToman);
  const symbol = prop.assetSymbol;
  const description = `فروش ملک ${symbol}${input.saleDatePersian ? ` — ${input.saleDatePersian}` : ""}`;

  const entry = await db.transaction(async (tx) => {
    const { assetAccountId } = await ensureRealEstateLedgerAccounts(tx);
    const usdAssetId = await ensureUsdAssetId(tx);

    const cashUnitPrice = D(await nativeUnitPriceUsd(cashAccount.assetId, input.userId ?? null, tx));
    const cashQuantity = cashUnitPrice.gt(0) ? D(saleValueUsd).div(cashUnitPrice).toString() : D(saleValueUsd).toString();

    const postings: any[] = [
      {
        accountId: assetAccountId,
        assetId: prop.p.assetId,
        quantity: "-1",
        baseValue: carrying.neg().toString(),
        memo: `خروج ملک به بهای ثبت‌شده — قیمت خرید: ${formatMoney(prop.p.purchasePriceToman ?? "0", "IRT")}`,
      },
      {
        accountId: cashAccount.id,
        assetId: cashAccount.assetId,
        quantity: cashQuantity,
        baseValue: D(saleValueUsd).toString(),
        memo: "واریز وجه فروش ملک",
      },
    ];

    if (!realizedUsd.isZero()) {
      const pnlAccount = await ensureRealizedPnlAccount(input.userId ?? null, tx);
      if (!pnlAccount) throw new Error("حساب سود سرمایه‌ای (۴۱۰۰) در دسترس نیست.");
      const pnlAssetId = pnlAccount.assetId ?? usdAssetId;
      const pnlUnitPrice = D(await nativeUnitPriceUsd(pnlAssetId, input.userId ?? null, tx));
      const pnlUnitsPerUsd = pnlUnitPrice.gt(0) ? D("1").div(pnlUnitPrice) : D("1");
      const pnlQuantity = realizedUsd.neg().mul(pnlUnitsPerUsd);
      postings.push({
        accountId: pnlAccount.id,
        assetId: pnlAssetId,
        quantity: pnlQuantity.isZero() ? realizedUsd.neg().toString() : pnlQuantity.toString(),
        baseValue: realizedUsd.neg().toString(),
        memo: "سود/زیان تحقق‌یافته از فروش ملک",
      });
    }

    const posted = await postEntry(
      {
        entryDate: saleDate,
        type: "sell",
        description,
        source: "manual",
        reference: symbol,
        userId: input.userId ?? undefined,
        idempotencyKey: `real-estate-sale:${prop.p.id}`,
        postings,
      },
      tx,
    );

    // Freeze the sale Toman + rate next to the ledger entry (audit + display).
    await tx
      .insert(entryFxSnapshots)
      .values({
        entryId: posted.id,
        irtAmount: salePrice.toFixed(0),
        usdAmount: D(saleValueUsd).toString(),
        fxRate: D(saleFx.rate).toString(),
        rateSource: saleFx.source,
        rateDate: saleFx.effectiveDate,
      })
      .onConflictDoNothing();

    // Remove the sold property from the portfolio (same cleanup as delete):
    // property row (cascade → valuation snapshots), soft-delete the asset and
    // release its identifier, drop the valuation cache. The ledger rows
    // (opening + sale) are immutable and stay intact.
    await tx.delete(realEstateProperties).where(eq(realEstateProperties.id, prop.p.id));
    await tx
      .update(assets)
      .set({
        deletedAt: new Date(),
        updatedAt: new Date(),
        symbol: `__del_${prop.p.assetId.replace(/-/g, "").slice(0, 16)}`,
      })
      .where(eq(assets.id, prop.p.assetId));
    await tx.delete(prices).where(eq(prices.assetId, prop.p.assetId));

    await recordAuditEvent(
      {
        action: "SELL_REAL_ESTATE_ASSET",
        entityType: "real_estate_property",
        entityId: prop.p.id,
        userId: input.userId ?? null,
        result: "SUCCESS",
        payload: {
          symbol,
          assetId: prop.p.assetId,
          saleDate,
          salePriceToman: salePrice.toFixed(0),
          saleValueUsd,
          saleFxRate: D(saleFx.rate).toString(),
          carryingUsd: carrying.toString(),
          realizedToman: realizedToman.toFixed(0),
          realizedUsd: realizedUsd.toString(),
          ledgerEntryId: posted.id,
        },
      },
      tx,
    );

    return { entryId: posted.id };
  });

  return {
    assetId: prop.p.assetId,
    symbol,
    ledgerEntryId: entry.entryId,
    saleValueUsd: D(saleValueUsd).toString(),
    realizedToman: realizedToman.toFixed(0),
    realizedUsd: realizedUsd.toString(),
  };
}

/* ─────────────────────── delete (proper cascade) ─────────────────────── */

/**
 * حذف کامل یک ملک — پاک‌سازی بدون آسیب به Accounting Core.
 *
 * این عمل:
 *  1. رکورد real_estate_properties را حذف می‌کند (FK cascade → valuation snapshots)
 *  2. دارایی (assets) را soft-delete می‌کند (deleted_at set)
 *     → getHoldings(), getPortfolioValuation() به‌طور خودکار آن را حذف می‌کنند
 *  3. ردیف‌های prices مربوطه را حذف می‌کند (valuation cache, not accounting)
 *  4. audit event ثبت می‌کند
 *
 * این عمل تغییر نمی‌دهد:
 *  ❌ journal_entries (immutable — ورودی دفترکل دست‌نخورده باقی می‌ماند)
 *  ❌ postings (immutable)
 *  ❌ accounts, lots, lot_consumptions, audit_log
 *
 * Note: journal entry مربوطه همچنان وجود دارد اما به‌دلیل فیلتر
 * getTransactions() (which excludes entries whose asset-type postings all
 * reference soft-deleted assets) در فعالیت‌های اخیر نمایش داده نمی‌شود.
 */
export async function deleteRealEstateAsset(input: {
  propertyId: string;
  userId?: string | null;
}): Promise<{ assetId: string; symbol: string }> {
  // 1. Load the property with its asset
  const [prop] = await db
    .select({
      p: realEstateProperties,
      assetSymbol: assets.symbol,
    })
    .from(realEstateProperties)
    .innerJoin(assets, eq(assets.id, realEstateProperties.assetId))
    .where(
      input.userId
        ? and(eq(realEstateProperties.id, input.propertyId), eq(realEstateProperties.userId, input.userId))
        : eq(realEstateProperties.id, input.propertyId),
    )
    .limit(1);

  if (!prop) throw new Error("ملک یافت نشد یا متعلق به شما نیست.");

  const assetId = prop.p.assetId;
  const symbol = prop.assetSymbol;

  await db.transaction(async (tx) => {
    // 2. Delete the property row (CASCADE → real_estate_valuation_snapshots)
    await tx.delete(realEstateProperties).where(eq(realEstateProperties.id, prop.p.id));

    // 3. Soft-delete the asset and RELEASE its compact identifier.
    // assets.symbol is globally unique, so a tombstone symbol is required
    // or the next live property could never reclaim `001`.
    await tx
      .update(assets)
      .set({
        deletedAt: new Date(),
        updatedAt: new Date(),
        symbol: `__del_${assetId.replace(/-/g, "").slice(0, 16)}`,
      })
      .where(eq(assets.id, assetId));

    // 4. Clean up prices for this asset (valuation cache, not accounting data)
    await tx.delete(prices).where(eq(prices.assetId, assetId));

    // 5. Audit trail
    await recordAuditEvent(
      {
        action: "DELETE_REAL_ESTATE_ASSET",
        entityType: "real_estate_property",
        entityId: prop.p.id,
        userId: input.userId ?? null,
        result: "SUCCESS",
        payload: {
          symbol,
          assetId,
          ledgerEntryId: prop.p.ledgerEntryId ?? null,
        },
      },
      tx,
    );
  });

  return { assetId, symbol };
}

/* ─────────────────────── repair orphaned data ─────────────────────── */

/**
 * شناسایی و پاک‌سازی دارایی‌های یتیم (orphaned) املاک.
 *
 * یک دارایی یتیم = یک ردیف در `assets` (کلاس RWA) که:
 *  - ردیف متناظر در real_estate_properties ندارد (حذف شده)
 *  - ردیف متناظر در vehicle_assets ندارد
 *  - ردیف متناظر در rwa_ownership_records ندارد (یا isActive=false)
 *  - soft-delete نشده (deleted_at IS NULL)
 *
 * برای هر دارایی یتیم:
 *  - assets.deleted_at را تنظیم می‌کند (soft-delete)
 *  - prices را پاک‌سازی می‌کند
 *
 * Non-destructive: journal_entries, postings, accounts تغییر نمی‌کنند.
 * Idempotent: اجرای مجدد هیچ اثری ندارد.
 */
export async function repairOrphanedRealEstate(): Promise<{ cleaned: number; details: string[] }> {
  // Find RWA assets that have no corresponding property, vehicle, or active ownership
  const orphanedRows = await db.execute(sql`
    SELECT a.id AS asset_id, a.symbol
    FROM assets a
    WHERE a.deleted_at IS NULL
      AND ${isOrphanedRwaAsset("a")}
  `);

  const rows = orphanedRows.rows as Array<{ asset_id: string; symbol: string }>;
  if (rows.length === 0) return { cleaned: 0, details: [] };

  const details: string[] = [];
  for (const row of rows) {
    await db
      .update(assets)
      .set({
        deletedAt: new Date(),
        updatedAt: new Date(),
        symbol: `__del_${row.asset_id.replace(/-/g, "").slice(0, 16)}`,
      })
      .where(eq(assets.id, row.asset_id));

    // Clean up prices for this asset
    await db.delete(prices).where(eq(prices.assetId, row.asset_id));

    details.push(`Asset ${row.symbol} (${row.asset_id}) — soft-deleted + prices cleaned`);

    await recordAuditEvent({
      action: "REPAIR_ORPHANED_RWA_ASSET",
      entityType: "asset",
      entityId: row.asset_id,
      userId: null,
      result: "SUCCESS",
      payload: { symbol: row.symbol, reason: "orphaned — no property/vehicle/ownership record" },
    });
  }

  return { cleaned: rows.length, details };
}

/* ─────────────────────── bootstrap / migration ─────────────────────── */

let readyPromise: Promise<void> | null = null;

/**
 * Prepare the real estate module:
 *  1. make sure the schema exists (idempotent, memoised),
 *  2. seed the master data once (dynamic afterwards),
 *  3. migrate legacy free-text rows onto the master-data identity when a
 *     confident match exists (city "Ahvaz" → AHZ, area by normalized name,
 *     property type by normalized name) — existing rows are preserved,
 *  4. backfill a frozen Toman snapshot for historical acquisitions created
 *     before the freeze existed (display-only, idempotent, never rewrites).
 *
 * NOTE: repairOrphanedRealEstate() is intentionally NOT called here.
 * Read paths must never trigger a write. Orphan filtering is handled in
 * read queries (getHoldings, getAccountBalances, getLedger, getTransactions,
 * getRealizedPnl, getOpenLots, historicalTomanCostByAsset, etc.), so reports
 * stay correct even before an explicit repair. Identifier reuse (e.g. 001)
 * also no longer depends on repair: nextRwaSymbol ignores orphans. The
 * repair itself is a separate mutation (see repairOrphanedRealEstateAction)
 * that soft-deletes the orphan asset and cleans price caches.
 */
export async function ensureRealEstateModuleReady(): Promise<void> {
  readyPromise ??= (async () => {
    await ensureSchemaOnce();
    await seedRealEstateMasterDataIfEmpty();
    await migrateLegacyPropertyRows();
    await backfillRealEstateFxSnapshots();
    await backfillRealEstateValuationSnapshots();
  })().catch((err) => {
    readyPromise = null;
    throw err;
  });
  return readyPromise;
}

/**
 * Backfill immutable valuation snapshots for properties created BEFORE the
 * snapshot history existed (additive migration, runs once per deployment).
 *
 * Idempotent + non-destructive:
 *  - seeds exactly ONE snapshot per property from its authoritative current
 *    valuation row (date + Toman value + frozen rate + USD value),
 *  - only inserts where no snapshot exists for that property+date,
 *  - never rewrites an existing snapshot and never invents values — older
 *    valuations whose Toman/rate were already overwritten cannot be
 *    reconstructed and are NOT guessed (see AUDIT-REAL-ASSETS doc).
 */
export async function backfillRealEstateValuationSnapshots(): Promise<{ inserted: number; skipped: number }> {
  const props = await db
    .select()
    .from(realEstateProperties)
    .where(
      and(
        isNotNull(realEstateProperties.currentValueToman),
        isNotNull(realEstateProperties.valuationDate),
        isNotNull(realEstateProperties.valuationFxRate),
        isNotNull(realEstateProperties.currentValueUsd),
      ),
    );

  let inserted = 0;
  let skipped = 0;
  for (const prop of props) {
    const [existing] = await db
      .select({ id: realEstateValuationSnapshots.id })
      .from(realEstateValuationSnapshots)
      .where(
        and(
          eq(realEstateValuationSnapshots.propertyId, prop.id),
          eq(realEstateValuationSnapshots.snapshotDate, prop.valuationDate!),
        ),
      )
      .limit(1);
    if (existing) {
      skipped++;
      continue;
    }
    await db
      .insert(realEstateValuationSnapshots)
      .values({
        propertyId: prop.id,
        assetId: prop.assetId,
        userId: prop.userId ?? null,
        snapshotDate: prop.valuationDate!,
        snapshotDatePersian: prop.valuationDatePersian ?? null,
        currentValueToman: D(prop.currentValueToman!).toFixed(0),
        usdRate: D(prop.valuationFxRate!).toString(),
        usdRateSource: prop.valuationFxRateSource ?? "manual",
        usdRateDate: prop.valuationFxRateDate ?? prop.valuationDate!,
        currentValueUsd: D(prop.currentValueUsd!).toString(),
        source: "manual",
        note: "بازسازی اسنپ‌شات از آخرین ارزش‌گذاری معتبر (Backfill)",
      })
      .onConflictDoNothing();
    inserted++;
  }
  return { inserted, skipped };
}

/**
 * Backfill a frozen Toman snapshot for real-estate opening entries created
 * before the freeze was introduced (see `postRealEstateOpeningEntry`).
 *
 * Idempotent + non-destructive:
 *  - only inserts where no `entry_fx_snapshots` row exists for the entry,
 *  - never rewrites an existing snapshot or any ledger/postings row,
 *  - only uses fields already stored on the property (purchase price in Toman,
 *    purchase USD value, historical FX rate) — never guesses financial data.
 */
export async function backfillRealEstateFxSnapshots(): Promise<{ inserted: number; skipped: number }> {
  const rows = await db
    .select()
    .from(realEstateProperties)
    .where(
      and(
        isNotNull(realEstateProperties.ledgerEntryId),
        isNotNull(realEstateProperties.purchasePriceToman),
        isNotNull(realEstateProperties.purchaseValueUsd),
        isNotNull(realEstateProperties.purchaseFxRate),
      ),
    );

  let inserted = 0;
  let skipped = 0;
  for (const prop of rows) {
    const entryId = prop.ledgerEntryId!;
    const [existing] = await db
      .select({ id: entryFxSnapshots.id })
      .from(entryFxSnapshots)
      .where(eq(entryFxSnapshots.entryId, entryId))
      .limit(1);
    if (existing) {
      skipped++;
      continue;
    }
    const rateDate = prop.purchaseFxRateDate ?? prop.acquisitionDate ?? prop.systemEntryDate;
    if (!rateDate) {
      skipped++;
      continue;
    }
    await db
      .insert(entryFxSnapshots)
      .values({
        entryId,
        irtAmount: D(prop.purchasePriceToman!).toFixed(0),
        usdAmount: D(prop.purchaseValueUsd!).toString(),
        fxRate: D(prop.purchaseFxRate!).toString(),
        rateSource: prop.purchaseFxRateSource ?? "manual",
        rateDate,
      })
      .onConflictDoNothing();
    inserted++;
  }
  return { inserted, skipped };
}

export async function migrateLegacyPropertyRows(): Promise<{ linked: number }> {
  const rows = await db.select().from(realEstateProperties).where(sql`city_id IS NULL`);
  if (rows.length === 0) return { linked: 0 };

  const cities = await listCities(true);
  const hoods = await listNeighborhoods(undefined, true);
  const types = await listPropertyTypes(true);
  const ahvaz = cities.find((c) => c.code === "AHZ");
  const hoodByKey = new Map(hoods.map((h) => [normalizeKey(h.nameFa), h]));
  const typeByKey = new Map(types.map((t) => [normalizeKey(t.nameFa), t]));
  const codeToType = new Map(types.map((t) => [t.code.toLowerCase(), t]));

  let linked = 0;
  for (const row of rows) {
    const patch: Partial<typeof realEstateProperties.$inferInsert> = {};
    const city = ahvaz && normalizeKey(row.city) === normalizeKey("Ahvaz") ? ahvaz : cities.find((c) => normalizeKey(c.nameFa) === normalizeKey(row.city));
    if (city) patch.cityId = city.id;
    if (city && row.area) {
      const hood = hoodByKey.get(normalizeKey(row.area));
      if (hood && hood.cityId === city.id) patch.neighborhoodId = hood.id;
    }
    const ptype = typeByKey.get(normalizeKey(row.propertyType)) ?? codeToType.get(normalizeKey(row.propertyType));
    if (ptype) patch.propertyTypeId = ptype.id;

    if (Object.keys(patch).length) {
      await db.update(realEstateProperties).set({ ...patch, updatedAt: new Date() }).where(eq(realEstateProperties.id, row.id));
      linked++;
    }
  }
  return { linked };
}

/* ─────────────────────── legacy compatibility ─────────────────────── */

/**
 * Legacy identity-only create (used by the old free-text form and by tests).
 * New registrations MUST use `createRealEstateAsset` — the free-text path is
 * kept only so existing code keeps working; it never generates names/symbols.
 */
export async function createRealEstateProperty(input: {
  assetId: string;
  userId?: string;
  propertyType?: string;
  city?: string;
  area?: string;
  address?: string;
  sizeSqm?: string;
  floor?: number;
  yearBuilt?: number;
  deedNumber?: string;
  notes?: string;
}): Promise<{ id: string }> {
  const [assetRow] = await db.select().from(assets).where(eq(assets.id, input.assetId)).limit(1);
  if (!assetRow) throw new Error(`Asset not found: ${input.assetId}`);

  const [inserted] = await db
    .insert(realEstateProperties)
    .values({
      assetId: input.assetId,
      userId: input.userId ?? null,
      propertyType: input.propertyType ?? "apartment",
      city: input.city ?? "Ahvaz",
      area: input.area ?? null,
      address: input.address ?? null,
      sizeSqm: input.sizeSqm ?? null,
      floor: input.floor ?? null,
      yearBuilt: input.yearBuilt ?? null,
      deedNumber: input.deedNumber ?? null,
      notes: input.notes ?? null,
    })
    .onConflictDoUpdate({
      target: realEstateProperties.assetId,
      set: {
        userId: input.userId ?? null,
        propertyType: input.propertyType ?? "apartment",
        city: input.city ?? "Ahvaz",
        area: input.area ?? null,
        address: input.address ?? null,
        sizeSqm: input.sizeSqm ?? null,
        floor: input.floor ?? null,
        yearBuilt: input.yearBuilt ?? null,
        deedNumber: input.deedNumber ?? null,
        notes: input.notes ?? null,
        updatedAt: new Date(),
      },
    })
    .returning();

  return { id: inserted.id };
}

/* Re-export shared module types for components/actions. */
export type {
  City,
  CreateRealEstateAssetInput,
  FxRateResolution,
  Neighborhood,
  PropertyType,
  RealEstateAsset,
  RealEstateHistoryRow,
  RealEstateNamePreview,
  RealEstatePeriodResult,
  RealEstatePerformance,
  RealEstatePortfolioSummary,
  RealEstateSnapshotPoint,
  RealEstateValuationSnapshot,
  RecordRealEstateValuationInput,
} from "./types";
