/**
 * RWA Real Estate Service — دارایی واقعی → املاک / Real Estate
 *
 * The property is a fully ACCOUNTED asset:
 *
 *   • Identity comes 100% from master data — the user never types the city,
 *     neighborhood, property type, asset name or symbol.
 *   • Name  → «آپارتمان — اهواز — کیانپارس شرقی» (+ sequential suffix for
 *             similar properties in the same area), generated by the system.
 *   • Symbol→ a compact global RWA id (`001`, `002`, …), generated, unique
 *             (DB unique constraint on assets.symbol) and immutable.
 *   • Dates → the user enters PERSIAN dates; the UI converts to Gregorian/ISO
 *             which is the standard stored value (Persian kept for display).
 *   • FX    → purchase uses the rate OF THE ACQUISITION DATE, current value
 *             uses the rate OF THE VALUATION DATE. Both rates are frozen next
 *             to the amounts and are fully auditable (rate + source + date).
 *   • Ledger→ a double-entry OPENING entry dated at the REAL acquisition date
 *             (Debit: Real Estate Asset / Credit: Opening Equity). A property
 *             bought before the system started is a PRIOR-PERIOD ACQUISITION:
 *             no cash outflow is ever created at the system-entry date.
 *   • Current value is updated ONLY by a new valuation — it never rewrites the
 *     immutable purchase history or the ledger.
 */
import { and, desc, eq, isNull, sql } from "drizzle-orm";
import { db } from "@/db";
import {
  accounts,
  assetClasses,
  assets,
  journalEntries,
  prices,
  postings,
  realEstateProperties,
} from "@/db/schema";
import { ensureSchemaOnce } from "@/db/init-schema";
import { D } from "@/domain/decimal";
import { todayIso } from "@/lib/format";
import { recordAuditEvent } from "@/lib/audit";
import { postEntry } from "@/features/ledger/service";
import { resolveUsdRateForDate, tomanToUsd } from "@/features/rwa/vehicle/fx";
import { formatMoney } from "@/lib/format";
import { buildRwaSymbol, nextRwaSymbol } from "@/features/rwa/symbol";
import {
  getCity,
  getNeighborhood,
  getPropertyType,
  listCities,
  listNeighborhoods,
  listPropertyTypes,
  normalizeKey,
  seedRealEstateMasterDataIfEmpty,
} from "./masterData";
import type {
  City,
  CreateRealEstateAssetInput,
  FxRateResolution,
  Neighborhood,
  PropertyType,
  RealEstateAsset,
  RealEstateNamePreview,
  RealEstatePerformance,
  RealEstatePortfolioSummary,
  RecordRealEstateValuationInput,
  UpdateRealEstatePurchasePriceInput,
} from "./types";

/* ─────────────────────── shared helpers ─────────────────────── */

async function ensureRwaAssetClassId(tx: any = db): Promise<string> {
  let [klass] = await tx.select().from(assetClasses).where(eq(assetClasses.code, "RWA")).limit(1);
  if (!klass) {
    [klass] = await tx
      .insert(assetClasses)
      .values({ code: "RWA", name: "دارایی واقعی", color: "#12131c", sortOrder: 90 })
      .onConflictDoNothing()
      .returning();
    if (!klass) [klass] = await tx.select().from(assetClasses).where(eq(assetClasses.code, "RWA")).limit(1);
  }
  if (!klass) throw new Error("کلاس دارایی واقعی ایجاد نشد.");
  return klass.id;
}

/** The ledger's base currency asset (equity leg of opening entries uses it). */
async function ensureUsdAssetId(tx: any = db): Promise<string> {
  let [usdAsset] = await tx.select().from(assets).where(eq(assets.symbol, "USD")).limit(1);
  if (!usdAsset) {
    const classId = await ensureRwaAssetClassId(tx);
    [usdAsset] = await tx
      .insert(assets)
      .values({ symbol: "USD", name: "دلار آمریکا", classId, decimals: 2, priceSource: "manual" })
      .onConflictDoNothing()
      .returning();
    if (!usdAsset) [usdAsset] = await tx.select().from(assets).where(eq(assets.symbol, "USD")).limit(1);
  }
  if (!usdAsset) throw new Error("دارایی پایه (USD) یافت نشد.");
  return usdAsset.id;
}

/**
 * Real Estate ledger accounts (global, consistent with the seeded chart of
 * accounts — 1xxx assets / 3xxx equity):
 *   1600  املاک و مستغلات                 (asset)
 *   3015  سرمایه افتتاحیه تملک‌های تاریخی (equity)
 */
async function ensureRealEstateLedgerAccounts(tx: any = db): Promise<{ assetAccountId: string; openingEquityAccountId: string }> {
  const getByCode = async (code: string) => {
    // Global chart-of-accounts rows (user_id NULL) — consistent with the seed.
    const [row] = await tx.select().from(accounts).where(and(eq(accounts.code, code), isNull(accounts.userId))).limit(1);
    return row ?? null;
  };

  let assetAccount = await getByCode("1600");
  if (!assetAccount) {
    [assetAccount] = await tx
      .insert(accounts)
      .values({ code: "1600", name: "املاک و مستغلات", type: "asset" })
      .onConflictDoNothing({ target: [accounts.userId, accounts.code] })
      .returning();
    if (!assetAccount) assetAccount = await getByCode("1600");
  }

  let equityAccount = await getByCode("3015");
  if (!equityAccount) {
    [equityAccount] = await tx
      .insert(accounts)
      .values({ code: "3015", name: "سرمایه افتتاحیه تملک‌های تاریخی (املاک)", type: "equity" })
      .onConflictDoNothing({ target: [accounts.userId, accounts.code] })
      .returning();
    if (!equityAccount) equityAccount = await getByCode("3015");
  }

  if (!assetAccount || !equityAccount) throw new Error("حساب‌های دفترکل املاک ایجاد نشدند.");
  return { assetAccountId: assetAccount.id, openingEquityAccountId: equityAccount.id };
}

/* ─────────────────────── name & symbol generation ─────────────────────── */

/**
 * Number of already-registered properties with the same
 * (city, neighborhood, property type) — drives the human-readable name suffix.
 * The compact symbol uses the separate global RWA sequence.
 */
async function nextPropertySequence(cityId: string, neighborhoodId: string, propertyTypeId: string): Promise<number> {
  const [row] = await db
    .select({ c: sql<number>`count(*)::int` })
    .from(realEstateProperties)
    .where(
      and(
        eq(realEstateProperties.cityId, cityId),
        eq(realEstateProperties.neighborhoodId, neighborhoodId),
        eq(realEstateProperties.propertyTypeId, propertyTypeId),
      ),
    );
  return (Number(row?.c ?? 0) || 0) + 1;
}

/** «آپارتمان — اهواز — کیانپارس شرقی» (+ «— 001» when similar assets exist). */
export function buildAssetName(p: PropertyType, city: City, hood: Neighborhood, sequence: number): string {
  const base = `${p.nameFa} — ${city.nameFa} — ${hood.nameFa}`;
  return sequence > 1 ? `${base} — ${String(sequence).padStart(3, "0")}` : base;
}

/** Compact canonical RWA id (`001`, `002`, …). Shared with vehicles. */
export function buildSymbol(sequence: number): string {
  return buildRwaSymbol(sequence);
}

/** Live preview of the generated name/symbol (used by the registration form). */
export async function previewRealEstateIdentity(
  cityId: string,
  neighborhoodId: string,
  propertyTypeId: string,
): Promise<RealEstateNamePreview | null> {
  const [city, hood, ptype] = await Promise.all([getCity(cityId), getNeighborhood(neighborhoodId), getPropertyType(propertyTypeId)]);
  if (!city || !hood || !ptype) return null;
  const sequence = await nextPropertySequence(cityId, neighborhoodId, propertyTypeId);
  return {
    assetName: buildAssetName(ptype, city, hood, sequence),
    // Preview is advisory; the final transaction resolves and locks again.
    symbol: await nextRwaSymbol(),
    sequence,
  };
}

/* ─────────────────────── performance (derived, never stored) ─────────────────────── */

export function computePerformance(
  purchaseToman: string | null,
  currentToman: string | null,
  purchaseUsd: string | null,
  currentUsd: string | null,
): RealEstatePerformance {
  if (!purchaseToman || !currentToman) {
    return { gainToman: null, roiToman: null, gainUsd: null, roiUsd: null };
  }
  const pT = D(purchaseToman);
  const cT = D(currentToman);
  const gainToman = cT.sub(pT);
  const roiToman = pT.gt(0) ? gainToman.div(pT).mul("100").toFixed(2) : null;
  let gainUsd: string | null = null;
  let roiUsd: string | null = null;
  if (purchaseUsd && currentUsd && D(purchaseUsd).gt(0)) {
    const pU = D(purchaseUsd);
    const cU = D(currentUsd);
    gainUsd = cU.sub(pU).toFixed(2);
    roiUsd = pU.gt(0) ? cU.sub(pU).div(pU).mul("100").toFixed(2) : null;
  }
  return { gainToman: gainToman.toFixed(0), roiToman, gainUsd, roiUsd };
}

/* ─────────────────────── mapping ─────────────────────── */

const num = (v: unknown): string | null => (v === null || v === undefined ? null : D(v as string).toString());
const tomanStr = (v: unknown): string | null => (v === null || v === undefined ? null : D(v as string).toFixed(0));
const usdStr = (v: unknown): string | null => (v === null || v === undefined ? null : D(v as string).toFixed(2));

type PropertyRow = typeof realEstateProperties.$inferSelect & {
  assetSymbol: string;
  assetName: string;
};

function mapAsset(r: PropertyRow): RealEstateAsset {
  return {
    id: r.id,
    assetId: r.assetId,
    symbol: r.assetSymbol,
    assetName: r.assetName,
    userId: r.userId,
    cityId: r.cityId ?? null,
    cityNameFa: null,
    cityNameEn: null,
    cityCode: null,
    neighborhoodId: r.neighborhoodId ?? null,
    neighborhoodNameFa: null,
    neighborhoodNameEn: null,
    neighborhoodCode: null,
    propertyTypeId: r.propertyTypeId ?? null,
    propertyTypeNameFa: null,
    propertyTypeNameEn: null,
    propertyTypeCode: null,
    propertyType: r.propertyType ?? null,
    area: r.area ?? null,
    address: r.address ?? null,
    sizeSqm: r.sizeSqm === null || r.sizeSqm === undefined ? null : D(r.sizeSqm).toFixed(2),
    floor: r.floor ?? null,
    yearBuilt: r.yearBuilt ?? null,
    deedNumber: r.deedNumber ?? null,
    notes: r.notes ?? null,
    acquisitionDate: r.acquisitionDate ?? null,
    acquisitionDatePersian: r.acquisitionDatePersian ?? null,
    valuationDate: r.valuationDate ?? null,
    valuationDatePersian: r.valuationDatePersian ?? null,
    systemEntryDate: r.systemEntryDate ?? null,
    isHistorical: r.isHistorical,
    purchasePriceToman: tomanStr(r.purchasePriceToman),
    purchaseFxRate: num(r.purchaseFxRate),
    purchaseFxRateSource: r.purchaseFxRateSource ?? null,
    purchaseFxRateDate: r.purchaseFxRateDate ?? null,
    purchaseValueUsd: usdStr(r.purchaseValueUsd),
    currentValueToman: tomanStr(r.currentValueToman),
    valuationFxRate: num(r.valuationFxRate),
    valuationFxRateSource: r.valuationFxRateSource ?? null,
    valuationFxRateDate: r.valuationFxRateDate ?? null,
    currentValueUsd: usdStr(r.currentValueUsd),
    ledgerEntryId: r.ledgerEntryId ?? null,
    createdAt: r.createdAt?.toISOString() ?? new Date().toISOString(),
    updatedAt: r.updatedAt?.toISOString() ?? null,
  };
}

/* ─────────────────────── ledger posting ─────────────────────── */

/**
 * The double-entry record of the acquisition, dated at the REAL ownership
 * date. Because the acquisition may predate the system, the credit side is
 * Opening Equity (opening balance / prior-period acquisition) — never a cash
 * outflow at the system-entry date.
 */
async function postRealEstateOpeningEntry(
  tx: any,
  input: {
    userId?: string | null;
    assetId: string;
    symbol: string;
    assetName: string;
    entryDate: string;
    acquisitionDatePersian: string | null;
    purchaseValueUsd: string;
    purchasePriceToman: string; // قیمت خرید واقعی کاربر (تومان)
  },
): Promise<string> {
  const { assetAccountId, openingEquityAccountId } = await ensureRealEstateLedgerAccounts(tx);
  const usdAssetId = await ensureUsdAssetId(tx);

  const result = await postEntry(
    {
      entryDate: input.entryDate,
      type: "opening",
      description: `تملک تاریخی — ${input.assetName} (${input.symbol})${input.acquisitionDatePersian ? ` — ${input.acquisitionDatePersian}` : ""} | قیمت خرید: ${formatMoney(input.purchasePriceToman, "IRT")}`,
      source: "manual",
      reference: input.symbol,
      userId: input.userId ?? undefined,
      idempotencyKey: `real-estate-acquisition:${input.assetId}`,
      postings: [
        {
          accountId: assetAccountId,
          assetId: input.assetId,
          quantity: "1",
          baseValue: input.purchaseValueUsd,
          memo: `تملک ملک — قیمت خرید: ${formatMoney(input.purchasePriceToman, "IRT")}`,
        },
        {
          accountId: openingEquityAccountId,
          assetId: usdAssetId,
          quantity: D(input.purchaseValueUsd).neg().toString(),
          baseValue: D(input.purchaseValueUsd).neg().toString(),
          memo: "افتتاحیه تملک تاریخی (Opening Balance)",
        },
      ],
    },
    tx,
  );
  return result.id;
}

/** Record the current (USD) value into the prices table so holdings /
 *  net-worth / portfolio read it automatically (qty 1 × latest price). */
async function recordCurrentPrice(
  tx: any,
  assetId: string,
  currentValueUsd: string,
  valuationDate: string,
): Promise<void> {
  if (D(currentValueUsd).lte(0)) return;
  await tx
    .insert(prices)
    .values({ assetId, asOf: valuationDate, priceBase: D(currentValueUsd).toString(), source: "real_estate_valuation" })
    .onConflictDoUpdate({
      target: [prices.assetId, prices.asOf],
      set: { priceBase: D(currentValueUsd).toString(), source: "real_estate_valuation" },
    });
}

/* ─────────────────────── create ─────────────────────── */

/**
 * ثبت ملک — تمام قواعد ماژول در یک تراکنش:
 *  1. شهر/محله/نوع ملک فقط از Master Data فعال
 *  2. نام و شناسه کوتاه خودکار (کاربر هیچ‌کدام را وارد نمی‌کند)
 *  3. تاریخ شمسی → میلادی (ISO) به‌عنوان مقدار استاندارد
 *  4. قیمت خرید: نرخ دلارِ تاریخ تملک؛ ارزش فعلی: نرخ دلارِ تاریخ ارزش‌گذاری
 *  5. سند افتتاحیه دفترکل با تاریخِ تملکِ واقعی (نه تاریخ ثبت در سیستم)
 *  6. ارزش فعلی واردِ Aggregate می‌شود (جدول prices → سبد و ارزش خالص)
 */
export async function createRealEstateAsset(input: CreateRealEstateAssetInput): Promise<{
  id: string;
  assetId: string;
  symbol: string;
  assetName: string;
  ledgerEntryId: string;
}> {
  if (!input.cityId || !input.neighborhoodId || !input.propertyTypeId) {
    throw new Error("شهر، منطقه/محله و نوع ملک باید از فهرست انتخاب شوند.");
  }
  const [city, hood, ptype] = await Promise.all([
    getCity(input.cityId),
    getNeighborhood(input.neighborhoodId),
    getPropertyType(input.propertyTypeId),
  ]);
  if (!city || !city.isActive) throw new Error("شهر انتخاب‌شده معتبر نیست.");
  if (!hood || hood.cityId !== city.id) throw new Error("محله انتخاب‌شده متعلق به این شهر نیست.");
  if (!hood.isActive) throw new Error("محله انتخاب‌شده غیرفعال است.");
  if (!ptype || !ptype.isActive) throw new Error("نوع ملک انتخاب‌شده معتبر نیست.");

  const acquisitionDate = (input.acquisitionDate || "").slice(0, 10);
  if (!acquisitionDate) throw new Error("تاریخ تملک (شمسی) الزامی است و باید معتبر باشد.");
  const valuationDate = (input.valuationDate || "").slice(0, 10);
  if (!valuationDate) throw new Error("تاریخ ارزش‌گذاری (شمسی) الزامی است و باید معتبر باشد.");

  const purchase = D(input.purchasePriceToman ?? "0");
  if (purchase.lte(0)) throw new Error("قیمت خرید (تومان) الزامی است و باید بزرگ‌تر از صفر باشد.");
  const current = D(input.currentValueToman ?? "0");
  if (current.lte(0)) throw new Error("ارزش فعلی (تومان) الزامی است و باید بزرگ‌تر از صفر باشد.");

  // Historical FX — the rate of the ACQUISITION date, frozen forever.
  let purchaseFx: FxRateResolution;
  if (input.purchaseFxRate && D(input.purchaseFxRate).gt(0)) {
    purchaseFx = { rate: D(input.purchaseFxRate).toString(), effectiveDate: acquisitionDate, source: "manual", isExact: true };
  } else {
    purchaseFx = await resolveUsdRateForDate(acquisitionDate, input.userId ?? null);
  }
  if (D(purchaseFx.rate).lte(0)) throw new Error("نرخ دلار تاریخ تملک در دسترس نیست.");
  const purchaseValueUsd = tomanToUsd(purchase.toFixed(0), purchaseFx.rate);

  // Historical FX — the rate of the VALUATION date, frozen forever.
  let valuationFx: FxRateResolution;
  if (input.valuationFxRate && D(input.valuationFxRate).gt(0)) {
    valuationFx = { rate: D(input.valuationFxRate).toString(), effectiveDate: valuationDate, source: "manual", isExact: true };
  } else {
    valuationFx = await resolveUsdRateForDate(valuationDate, input.userId ?? null);
  }
  if (D(valuationFx.rate).lte(0)) throw new Error("نرخ دلار تاریخ ارزش‌گذاری در دسترس نیست.");
  const currentValueUsd = tomanToUsd(current.toFixed(0), valuationFx.rate);

  const sequence = await nextPropertySequence(city.id, hood.id, ptype.id);
  const assetName = buildAssetName(ptype, city, hood, sequence);
  const systemEntryDate = todayIso();
  const isHistorical = acquisitionDate < systemEntryDate;

  const classId = await ensureRwaAssetClassId();

  const created = await db.transaction(async (tx) => {
    const symbol = await nextRwaSymbol(tx, classId);
    const [asset] = await tx
      .insert(assets)
      .values({ name: assetName, symbol, classId, decimals: 2, priceSource: "manual" })
      .returning();
    if (!asset) throw new Error("ایجاد رکورد دارایی ناموفق بود.");

    const [prop] = await tx
      .insert(realEstateProperties)
      .values({
        assetId: asset.id,
        userId: input.userId ?? null,
        // master-data identity
        cityId: city.id,
        neighborhoodId: hood.id,
        propertyTypeId: ptype.id,
        // legacy denormalised copies (kept in sync for old consumers)
        city: city.nameEn,
        area: hood.nameEn,
        propertyType: ptype.code.toLowerCase(),
        address: input.address?.trim() || null,
        sizeSqm: input.sizeSqm ? D(input.sizeSqm).toString() : null,
        floor: input.floor ?? null,
        yearBuilt: input.yearBuilt ?? null,
        deedNumber: input.deedNumber?.trim() || null,
        notes: input.notes?.trim() || null,
        // timing
        acquisitionDate,
        acquisitionDatePersian: input.acquisitionDatePersian || null,
        valuationDate,
        valuationDatePersian: input.valuationDatePersian || null,
        systemEntryDate,
        isHistorical,
        // purchase
        purchasePriceToman: purchase.toFixed(0),
        purchaseFxRate: D(purchaseFx.rate).toString(),
        purchaseFxRateSource: purchaseFx.source,
        purchaseFxRateDate: purchaseFx.effectiveDate,
        purchaseValueUsd,
        // current valuation
        currentValueToman: current.toFixed(0),
        valuationFxRate: D(valuationFx.rate).toString(),
        valuationFxRateSource: valuationFx.source,
        valuationFxRateDate: valuationFx.effectiveDate,
        currentValueUsd,
      })
      .returning();

    const ledgerEntryId = await postRealEstateOpeningEntry(tx, {
      userId: input.userId ?? null,
      assetId: asset.id,
      symbol,
      assetName,
      entryDate: acquisitionDate,
      acquisitionDatePersian: input.acquisitionDatePersian || null,
      purchaseValueUsd,
      purchasePriceToman: purchase.toFixed(0),
    });

    await tx
      .update(realEstateProperties)
      .set({ ledgerEntryId, updatedAt: new Date() })
      .where(eq(realEstateProperties.id, prop.id));

    await recordCurrentPrice(tx, asset.id, currentValueUsd, valuationDate);

    await recordAuditEvent(
      {
        action: "CREATE_REAL_ESTATE_ASSET",
        entityType: "real_estate_property",
        entityId: prop.id,
        userId: input.userId ?? null,
        result: "SUCCESS",
        payload: {
          symbol,
          assetName,
          acquisitionDate,
          valuationDate,
          purchaseValueUsd,
          currentValueUsd,
          ledgerEntryId,
          isHistorical,
        },
      },
      tx,
    );

    return { id: prop.id, assetId: asset.id, ledgerEntryId, symbol };
  });

  return { ...created, assetName };
}

/* ─────────────────────── reads / dashboard ─────────────────────── */

// SECURITY (multi-user isolation): scoping MUST happen at the DB query level
// (WHERE user_id = :currentUserId), never via post-filtering in application code.
// When a `userId` is provided, only rows owned by that tenant are returned;
// NULL-owned private rows are NOT shared/system data and stay excluded.
async function loadProperties(userId?: string | null): Promise<RealEstateAsset[]> {
  const rows = await db
    .select({
      p: realEstateProperties,
      assetSymbol: assets.symbol,
      assetName: assets.name,
    })
    .from(realEstateProperties)
    .innerJoin(assets, eq(assets.id, realEstateProperties.assetId))
    .where(userId ? eq(realEstateProperties.userId, userId) : undefined)
    .orderBy(desc(realEstateProperties.createdAt));

  const filtered = rows;

  const cities = await listCities(true);
  const hoods = await listNeighborhoods(undefined, true);
  const types = await listPropertyTypes(true);
  const cityById = new Map(cities.map((c) => [c.id, c]));
  const hoodById = new Map(hoods.map((h) => [h.id, h]));
  const typeById = new Map(types.map((t) => [t.id, t]));

  return filtered.map(({ p, assetSymbol, assetName }) => {
    const asset = mapAsset({ ...p, assetSymbol, assetName });
    const c = asset.cityId ? cityById.get(asset.cityId) : null;
    const h = asset.neighborhoodId ? hoodById.get(asset.neighborhoodId) : null;
    const t = asset.propertyTypeId ? typeById.get(asset.propertyTypeId) : null;
    return {
      ...asset,
      cityNameFa: c?.nameFa ?? asset.cityNameFa,
      cityNameEn: c?.nameEn ?? asset.cityNameEn,
      cityCode: c?.code ?? asset.cityCode,
      neighborhoodNameFa: h?.nameFa ?? asset.neighborhoodNameFa,
      neighborhoodNameEn: h?.nameEn ?? asset.neighborhoodNameEn,
      neighborhoodCode: h?.code ?? asset.neighborhoodCode,
      propertyTypeNameFa: t?.nameFa ?? asset.propertyTypeNameFa,
      propertyTypeNameEn: t?.nameEn ?? asset.propertyTypeNameEn,
      propertyTypeCode: t?.code ?? asset.propertyTypeCode,
    };
  });
}

export async function listRealEstateAssets(userId?: string | null): Promise<RealEstateAsset[]> {
  return loadProperties(userId);
}

export async function getRealEstateAsset(propertyId: string): Promise<RealEstateAsset | null> {
  const [row] = await db
    .select({ p: realEstateProperties, assetSymbol: assets.symbol, assetName: assets.name })
    .from(realEstateProperties)
    .innerJoin(assets, eq(assets.id, realEstateProperties.assetId))
    .where(eq(realEstateProperties.id, propertyId))
    .limit(1);
  if (!row) return null;
  const asset = mapAsset({ ...row.p, assetSymbol: row.assetSymbol, assetName: row.assetName });
  const [city, hood, ptype] = await Promise.all([
    asset.cityId ? getCity(asset.cityId) : null,
    asset.neighborhoodId ? getNeighborhood(asset.neighborhoodId) : null,
    asset.propertyTypeId ? getPropertyType(asset.propertyTypeId) : null,
  ]);
  return {
    ...asset,
    cityNameFa: city?.nameFa ?? asset.cityNameFa,
    cityNameEn: city?.nameEn ?? asset.cityNameEn,
    cityCode: city?.code ?? asset.cityCode,
    neighborhoodNameFa: hood?.nameFa ?? asset.neighborhoodNameFa,
    neighborhoodNameEn: hood?.nameEn ?? asset.neighborhoodNameEn,
    neighborhoodCode: hood?.code ?? asset.neighborhoodCode,
    propertyTypeNameFa: ptype?.nameFa ?? asset.propertyTypeNameFa,
    propertyTypeNameEn: ptype?.nameEn ?? asset.propertyTypeNameEn,
    propertyTypeCode: ptype?.code ?? asset.propertyTypeCode,
  };
}

export type RealEstateDashboardItem = RealEstateAsset & {
  performance: RealEstatePerformance;
};

export async function getRealEstateDashboard(userId?: string | null): Promise<RealEstateDashboardItem[]> {
  const assetsList = await loadProperties(userId);
  return assetsList.map((a) => ({
    ...a,
    performance: computePerformance(a.purchasePriceToman, a.currentValueToman, a.purchaseValueUsd, a.currentValueUsd),
  }));
}

export async function getRealEstatePortfolioSummary(userId?: string | null): Promise<RealEstatePortfolioSummary> {
  const dashboard = await getRealEstateDashboard(userId);

  let totalCurrentToman = D("0");
  let totalCurrentUsd = D("0");
  let totalPurchaseToman = D("0");
  let totalPurchaseUsd = D("0");
  let unvaluedCount = 0;

  for (const a of dashboard) {
    if (!a.currentValueToman) unvaluedCount++;
    if (a.currentValueToman) totalCurrentToman = totalCurrentToman.add(a.currentValueToman);
    if (a.currentValueUsd) totalCurrentUsd = totalCurrentUsd.add(a.currentValueUsd);
    if (a.purchasePriceToman) totalPurchaseToman = totalPurchaseToman.add(a.purchasePriceToman);
    if (a.purchaseValueUsd) totalPurchaseUsd = totalPurchaseUsd.add(a.purchaseValueUsd);
  }

  const totalGainToman = totalCurrentToman.sub(totalPurchaseToman);
  const totalGainUsd = totalCurrentUsd.sub(totalPurchaseUsd);

  return {
    count: dashboard.length,
    unvaluedCount,
    totalCurrentToman: totalCurrentToman.toFixed(0),
    totalCurrentUsd: totalCurrentUsd.toFixed(2),
    totalPurchaseToman: totalPurchaseToman.toFixed(0),
    totalPurchaseUsd: totalPurchaseUsd.toFixed(2),
    totalGainToman: totalGainToman.toFixed(0),
    totalGainUsd: totalGainUsd.toFixed(2),
    roiToman: totalPurchaseToman.gt(0) ? totalGainToman.div(totalPurchaseToman).mul("100").toFixed(2) : null,
    roiUsd: totalPurchaseUsd.gt(0) ? totalGainUsd.div(totalPurchaseUsd).mul("100").toFixed(2) : null,
  };
}

/* ─────────────────────── revaluation (append-only) ─────────────────────── */

/**
 * ارزش‌گذاری جدید — Current Value changes ONLY here.
 *  - The ledger entry and the purchase history are NEVER touched (immutable).
 *  - A new price row (prices) makes the aggregate / net-worth use the new value.
 */
export async function recordRealEstateValuation(input: RecordRealEstateValuationInput): Promise<{
  id: string;
  currentValueToman: string;
  currentValueUsd: string;
  valuationFxRate: string;
}> {
  // SECURITY (H-01): tenancy boundary enforced at the DATABASE query level.
  // When a user identity is present (multi-user mode), the property is only
  // loadable if it belongs to that exact user — a cross-user propertyId
  // simply does not exist for this caller (404 semantics, nothing leaks and
  // nothing can be mutated). In legacy single-tenant mode there is no
  // identity to scope by, so the global lookup is kept.
  const [prop] = await db
    .select()
    .from(realEstateProperties)
    .where(
      input.userId
        ? and(eq(realEstateProperties.id, input.propertyId), eq(realEstateProperties.userId, input.userId))
        : eq(realEstateProperties.id, input.propertyId),
    )
    .limit(1);
  if (!prop) throw new Error("ملک یافت نشد یا متعلق به شما نیست.");

  const valuationDate = (input.valuationDate || "").slice(0, 10);
  if (!valuationDate) throw new Error("تاریخ ارزش‌گذاری (شمسی) الزامی است.");
  const current = D(input.currentValueToman ?? "0");
  if (current.lte(0)) throw new Error("ارزش فعلی باید بزرگ‌تر از صفر باشد.");

  let valuationFx: FxRateResolution;
  if (input.valuationFxRate && D(input.valuationFxRate).gt(0)) {
    valuationFx = { rate: D(input.valuationFxRate).toString(), effectiveDate: valuationDate, source: "manual", isExact: true };
  } else {
    valuationFx = await resolveUsdRateForDate(valuationDate, input.userId ?? null);
  }
  if (D(valuationFx.rate).lte(0)) throw new Error("نرخ دلار تاریخ ارزش‌گذاری در دسترس نیست.");
  const currentValueUsd = tomanToUsd(current.toFixed(0), valuationFx.rate);

  const updated = await db.transaction(async (tx) => {
    const [row] = await tx
      .update(realEstateProperties)
      .set({
        currentValueToman: current.toFixed(0),
        valuationFxRate: D(valuationFx.rate).toString(),
        valuationFxRateSource: valuationFx.source,
        valuationFxRateDate: valuationFx.effectiveDate,
        currentValueUsd,
        valuationDate,
        valuationDatePersian: input.valuationDatePersian ?? null,
        updatedAt: new Date(),
      })
      .where(eq(realEstateProperties.id, prop.id))
      .returning();

    await recordCurrentPrice(tx, prop.assetId, currentValueUsd, valuationDate);

    await recordAuditEvent(
      {
        action: "REVALUE_REAL_ESTATE_ASSET",
        entityType: "real_estate_property",
        entityId: prop.id,
        userId: input.userId ?? null,
        result: "SUCCESS",
        payload: {
          valuationDate,
          currentValueToman: current.toFixed(0),
          currentValueUsd,
          valuationFxRate: D(valuationFx.rate).toString(),
          source: valuationFx.source,
          ledgerEntryId: prop.ledgerEntryId,
        },
      },
      tx,
    );

    return row;
  });

  if (!updated) throw new Error("به‌روزرسانی ارزش‌گذاری ناموفق بود.");
  return {
    id: updated.id,
    currentValueToman: D(updated.currentValueToman ?? "0").toFixed(0),
    currentValueUsd: D(updated.currentValueUsd ?? "0").toFixed(2),
    valuationFxRate: D(updated.valuationFxRate ?? "0").toString(),
  };
}

/* ─────────────────────── bootstrap / migration ─────────────────────── */

let readyPromise: Promise<void> | null = null;

/**
 * Prepare the real estate module:
 *  1. make sure the schema exists (idempotent, memoised),
 *  2. seed the master data once (dynamic afterwards),
 *  3. migrate legacy free-text rows onto the master-data identity when a
 *     confident match exists (city "Ahvaz" → AHZ, area by normalized name,
 *     property type by normalized name) — existing rows are preserved.
 */
export async function ensureRealEstateModuleReady(): Promise<void> {
  readyPromise ??= (async () => {
    await ensureSchemaOnce();
    await seedRealEstateMasterDataIfEmpty();
    await migrateLegacyPropertyRows();
  })().catch((err) => {
    readyPromise = null;
    throw err;
  });
  return readyPromise;
}

export async function migrateLegacyPropertyRows(): Promise<{ linked: number }> {
  const rows = await db.select().from(realEstateProperties).where(sql`city_id IS NULL`);
  if (rows.length === 0) return { linked: 0 };

  const cities = await listCities(true);
  const hoods = await listNeighborhoods(undefined, true);
  const types = await listPropertyTypes(true);
  const ahvaz = cities.find((c) => c.code === "AHZ");
  const hoodByKey = new Map(hoods.map((h) => [normalizeKey(h.nameFa), h]));
  const typeByKey = new Map(types.map((t) => [normalizeKey(t.nameFa), t]));
  const codeToType = new Map(types.map((t) => [t.code.toLowerCase(), t]));

  let linked = 0;
  for (const row of rows) {
    const patch: Partial<typeof realEstateProperties.$inferInsert> = {};
    const city = ahvaz && normalizeKey(row.city) === normalizeKey("Ahvaz") ? ahvaz : cities.find((c) => normalizeKey(c.nameFa) === normalizeKey(row.city));
    if (city) patch.cityId = city.id;
    if (city && row.area) {
      const hood = hoodByKey.get(normalizeKey(row.area));
      if (hood && hood.cityId === city.id) patch.neighborhoodId = hood.id;
    }
    const ptype = typeByKey.get(normalizeKey(row.propertyType)) ?? codeToType.get(normalizeKey(row.propertyType));
    if (ptype) patch.propertyTypeId = ptype.id;

    if (Object.keys(patch).length) {
      await db.update(realEstateProperties).set({ ...patch, updatedAt: new Date() }).where(eq(realEstateProperties.id, row.id));
      linked++;
    }
  }
  return { linked };
}

/* ─────────────────────── legacy compatibility ─────────────────────── */

/**
 * Legacy identity-only create (used by the old free-text form and by tests).
 * New registrations MUST use `createRealEstateAsset` — the free-text path is
 * kept only so existing code keeps working; it never generates names/symbols.
 */
export async function createRealEstateProperty(input: {
  assetId: string;
  userId?: string;
  propertyType?: string;
  city?: string;
  area?: string;
  address?: string;
  sizeSqm?: string;
  floor?: number;
  yearBuilt?: number;
  deedNumber?: string;
  notes?: string;
}): Promise<{ id: string }> {
  const [assetRow] = await db.select().from(assets).where(eq(assets.id, input.assetId)).limit(1);
  if (!assetRow) throw new Error(`Asset not found: ${input.assetId}`);

  const [inserted] = await db
    .insert(realEstateProperties)
    .values({
      assetId: input.assetId,
      userId: input.userId ?? null,
      propertyType: input.propertyType ?? "apartment",
      city: input.city ?? "Ahvaz",
      area: input.area ?? null,
      address: input.address ?? null,
      sizeSqm: input.sizeSqm ?? null,
      floor: input.floor ?? null,
      yearBuilt: input.yearBuilt ?? null,
      deedNumber: input.deedNumber ?? null,
      notes: input.notes ?? null,
    })
    .onConflictDoUpdate({
      target: realEstateProperties.assetId,
      set: {
        userId: input.userId ?? null,
        propertyType: input.propertyType ?? "apartment",
        city: input.city ?? "Ahvaz",
        area: input.area ?? null,
        address: input.address ?? null,
        sizeSqm: input.sizeSqm ?? null,
        floor: input.floor ?? null,
        yearBuilt: input.yearBuilt ?? null,
        deedNumber: input.deedNumber ?? null,
        notes: input.notes ?? null,
        updatedAt: new Date(),
      },
    })
    .returning();

  return { id: inserted.id };
}

/* ─────────────────────── purchase price correction ─────────────────────── */

/**
 * ویرایش قیمت خرید — برای اصلاح خطاهای ورود داده.
 * 
 * ⚠️ این تابع فقط برای اصلاح خطاهای ورود داده استفاده می‌شود.
 * ⚠️ تاریخ تملک و سایر اطلاعات تغییر نمی‌کند.
 * ⚠️ ارزش فعلی (currentValue) تغییر نمی‌کند.
 * 
 * این تابع:
 * 1. purchasePriceToman و purchaseFxRate و purchaseValueUsd را به‌روزرسانی می‌کند
 * 2. سند دفترکل را با توضیحات جدید به‌روزرسانی می‌کند
 */
export async function updateRealEstatePurchasePrice(input: UpdateRealEstatePurchasePriceInput): Promise<{
  id: string;
  purchasePriceToman: string;
  purchaseValueUsd: string;
  purchaseFxRate: string;
}> {
  // Load the property with tenant isolation
  const [row] = await db
    .select({
      p: realEstateProperties,
      assetSymbol: assets.symbol,
      assetName: assets.name,
    })
    .from(realEstateProperties)
    .innerJoin(assets, eq(assets.id, realEstateProperties.assetId))
    .where(
      input.userId
        ? and(eq(realEstateProperties.id, input.propertyId), eq(realEstateProperties.userId, input.userId))
        : eq(realEstateProperties.id, input.propertyId),
    )
    .limit(1);
  if (!row) throw new Error("ملک یافت نشد یا متعلق به شما نیست.");

  const prop = row.p;
  const asset = row;

  const acquisitionDate = prop.acquisitionDate;
  if (!acquisitionDate) throw new Error("تاریخ تملک ملک یافت نشد.");

  const purchase = D(input.purchasePriceToman ?? "0");
  if (purchase.lte(0)) throw new Error("قیمت خرید باید بزرگ‌تر از صفر باشد.");

  // Resolve FX rate
  let purchaseFx: FxRateResolution;
  if (input.purchaseFxRate && D(input.purchaseFxRate).gt(0)) {
    purchaseFx = { rate: D(input.purchaseFxRate).toString(), effectiveDate: acquisitionDate, source: "manual", isExact: true };
  } else {
    purchaseFx = await resolveUsdRateForDate(acquisitionDate, input.userId ?? null);
  }
  if (D(purchaseFx.rate).lte(0)) throw new Error("نرخ دلار تاریخ تملک در دسترس نیست.");
  const purchaseValueUsd = tomanToUsd(purchase.toFixed(0), purchaseFx.rate);

  const updated = await db.transaction(async (tx) => {
    // Update property record
    const [updatedRow] = await tx
      .update(realEstateProperties)
      .set({
        purchasePriceToman: purchase.toFixed(0),
        purchaseFxRate: D(purchaseFx.rate).toString(),
        purchaseFxRateSource: purchaseFx.source,
        purchaseFxRateDate: purchaseFx.effectiveDate,
        purchaseValueUsd,
        updatedAt: new Date(),
      })
      .where(eq(realEstateProperties.id, prop.id))
      .returning();

    // Update ledger entry description if exists
    if (prop.ledgerEntryId) {
      const newMemo = `تملک ملک — قیمت خرید: ${formatMoney(purchase.toFixed(0), "IRT")}`;
      
      await tx
        .update(postings)
        .set({ memo: newMemo })
        .where(
          and(
            eq(postings.entryId, prop.ledgerEntryId),
            sql`asset_id = ${prop.assetId}`
          )
        );
    }

    await recordAuditEvent(
      {
        action: "UPDATE_REAL_ESTATE_PURCHASE_PRICE",
        entityType: "real_estate_property",
        entityId: prop.id,
        userId: input.userId ?? null,
        result: "SUCCESS",
        payload: {
          previousPurchasePriceToman: prop.purchasePriceToman,
          newPurchasePriceToman: purchase.toFixed(0),
          purchaseFxRate: D(purchaseFx.rate).toString(),
          purchaseValueUsd,
          ledgerEntryId: prop.ledgerEntryId,
        },
      },
      tx,
    );

    return updatedRow;
  });

  if (!updated) throw new Error("به‌روزرسانی قیمت خرید ناموفق بود.");
  return {
    id: updated.id,
    purchasePriceToman: D(updated.purchasePriceToman ?? "0").toFixed(0),
    purchaseValueUsd: D(updated.purchaseValueUsd ?? "0").toFixed(2),
    purchaseFxRate: D(updated.purchaseFxRate ?? "0").toString(),
  };
}

/* Re-export shared module types for components/actions. */
export type {
  City,
  CreateRealEstateAssetInput,
  FxRateResolution,
  Neighborhood,
  PropertyType,
  RealEstateAsset,
  RealEstateNamePreview,
  RealEstatePerformance,
  RealEstatePortfolioSummary,
  RecordRealEstateValuationInput,
  UpdateRealEstatePurchasePriceInput,
} from "./types";
