/**
 * Real Estate module types — دارایی واقعی → املاک / Real Estate
 *
 * Conceptual model:
 *
 *   Master Data (City → Neighborhood → Property Type)   ← extensible, active-only
 *        ↓
 *   Real Estate Asset  (name + symbol GENERATED by the system, never typed)
 *        ↓
 *   Purchase (historical, immutable)  →  Current Valuation (append-only)
 *        ↓
 *   General Ledger (opening entry dated at the REAL acquisition date)
 *
 * The symbol is 100% system-generated, unique and immutable. It uses the
 * compact global RWA sequence (`001`, `002`, …); location/type identity stays
 * in the relational master-data fields instead of being duplicated in it.
 */

export type FxRateResolution = {
  rate: string;
  /** date of the rate that was actually used */
  effectiveDate: string;
  /** exact | nearest | current | manual | fallback */
  source: string;
  /** true when a rate for the exact requested date existed */
  isExact: boolean;
};

export type City = {
  id: string;
  nameFa: string;
  nameEn: string;
  code: string;
  isActive: boolean;
  sortOrder: number;
};

export type Neighborhood = {
  id: string;
  cityId: string;
  nameFa: string;
  nameEn: string;
  code: string;
  isActive: boolean;
  sortOrder: number;
};

export type PropertyType = {
  id: string;
  nameFa: string;
  nameEn: string;
  code: string;
  isActive: boolean;
  sortOrder: number;
};

/** One registered real estate asset with everything needed for display. */
export type RealEstateAsset = {
  id: string;
  assetId: string;
  symbol: string;
  assetName: string;
  userId: string | null;
  /* master data */
  cityId: string | null;
  cityNameFa: string | null;
  cityNameEn: string | null;
  cityCode: string | null;
  neighborhoodId: string | null;
  neighborhoodNameFa: string | null;
  neighborhoodNameEn: string | null;
  neighborhoodCode: string | null;
  propertyTypeId: string | null;
  propertyTypeNameFa: string | null;
  propertyTypeNameEn: string | null;
  propertyTypeCode: string | null;
  /* legacy denormalised identity (old free-text rows, fallback display) */
  propertyType: string | null;
  area: string | null;
  /* optional physical details */
  address: string | null;
  sizeSqm: string | null;
  floor: number | null;
  yearBuilt: number | null;
  deedNumber: string | null;
  notes: string | null;
  /* timing */
  acquisitionDate: string | null; // ISO
  acquisitionDatePersian: string | null;
  valuationDate: string | null; // ISO
  valuationDatePersian: string | null;
  systemEntryDate: string | null; // ISO
  isHistorical: boolean;
  /* purchase (historical, frozen) */
  purchasePriceToman: string | null;
  purchaseFxRate: string | null;
  purchaseFxRateSource: string | null;
  purchaseFxRateDate: string | null;
  purchaseValueUsd: string | null;
  /* current valuation (changes only by a NEW valuation) */
  currentValueToman: string | null;
  valuationFxRate: string | null;
  valuationFxRateSource: string | null;
  valuationFxRateDate: string | null;
  currentValueUsd: string | null;
  /* ledger link */
  ledgerEntryId: string | null;
  createdAt: string;
  updatedAt: string | null;
};

/** P&L is derived at read time — never stored (unrealized, display only). */
export type RealEstatePerformance = {
  gainToman: string | null;
  roiToman: string | null;
  gainUsd: string | null;
  roiUsd: string | null;
};

/**
 * IMMUTABLE historical valuation record — append-only, one per property per
 * date. Stores the Toman value AND the USD rate of the snapshot date, so the
 * USD figure of any past valuation can never be re-derived with today's rate.
 */
export type RealEstateValuationSnapshot = {
  id: string;
  propertyId: string;
  assetId: string;
  userId: string | null;
  snapshotDate: string; // ISO
  snapshotDatePersian: string | null;
  currentValueToman: string;
  usdRate: string;
  usdRateSource: string | null;
  usdRateDate: string | null;
  currentValueUsd: string;
  source: string;
  note: string | null;
  createdAt: string;
};

/** نقشهٔ ارزش یک تاریخ مشخص — مبنا یا مبین هر مقایسهٔ بازه‌ای. */
export type RealEstateSnapshotPoint = {
  date: string;
  valueToman: string;
  usdRate: string;
  valueUsd: string;
};

export type RealEstateHistoryRow = RealEstateSnapshotPoint & {
  tomanChange?: string | null;
  tomanChangePct?: string | null;
  usdChange?: string | null;
  usdChangePct?: string | null;
};

/** نتیجهٔ یک بازهٔ استاندارد (۱م/۳م/۶م/۱س/…/تملک/کل دوره). */
export type RealEstatePeriodResult =
  | {
      available: true;
      key: string;
      label: string;
      from: RealEstateSnapshotPoint;
      to: RealEstateSnapshotPoint;
      /** true when the baseline is the purchase record rather than a snapshot */
      baselineIsPurchase?: boolean;
      tomanChange: string;
      tomanChangePct: string | null;
      usdChange: string;
      usdChangePct: string | null;
    }
  | { available: false; key: string; label: string; reason: string };

export type RealEstatePortfolioSummary = {
  count: number;
  /** properties without any valuation yet */
  unvaluedCount: number;
  totalCurrentToman: string;
  totalCurrentUsd: string;
  totalPurchaseToman: string;
  totalPurchaseUsd: string;
  totalGainToman: string;
  totalGainUsd: string;
  roiToman: string | null;
  roiUsd: string | null;
};

export type CreateRealEstateAssetInput = {
  userId?: string | null;
  /* master data (must be ACTIVE) */
  cityId: string;
  neighborhoodId: string;
  propertyTypeId: string;
  /* dates — the UI sends the Gregorian/ISO values it computed from the
     user's Persian input; Persian display strings are stored alongside */
  acquisitionDate: string;
  acquisitionDatePersian?: string | null;
  valuationDate: string;
  valuationDatePersian?: string | null;
  /* amounts (Toman, manual input) */
  purchasePriceToman: string;
  currentValueToman: string;
  /* optional manual FX overrides; empty → system FX engine for that date */
  purchaseFxRate?: string;
  valuationFxRate?: string;
  /* optional physical details */
  address?: string | null;
  sizeSqm?: string | null;
  floor?: number | null;
  yearBuilt?: number | null;
  deedNumber?: string | null;
  notes?: string | null;
};

export type RecordRealEstateValuationInput = {
  propertyId: string;
  userId?: string | null;
  valuationDate: string;
  valuationDatePersian?: string | null;
  currentValueToman: string;
  /** optional manual override; default = FX rate of the valuation date */
  valuationFxRate?: string;
  note?: string | null;
};

export type RealEstateNamePreview = {
  assetName: string;
  symbol: string;
  sequence: number;
};
